### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by fsimonis**
## How to work with this template

* [x] assign a release manager, who takes care of the process
* [ ] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Step by step guide

* [x] Look over [`CHANGELOG.md`](https://github.com/precice/precice/blob/develop/CHANGELOG.md) (all)
   * Add things, if necessary
   * Extract summary
   * Fix wording
   * Sort the entries lexicographically
* [x] Look over the [Roadmap](https://github.com/precice/precice/wiki/Roadmap) and update entries.
* [x] Merge master to develop (No commits after the release on master)
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [x] Create branch `release-N` from develop. If needed, `git rebase develop`.
* [x] Open PR from `release-N` to `master` (use [this template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md))
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version
* [x] Verify the version changes in:
   * [x] [CHANGELOG](https://github.com/precice/precice/blob/release-2.1.0/CHANGELOG.md)
   * [x] [CMakeLists.txt](https://github.com/precice/precice/blob/develop/CMakeLists.txt)
   * [x] [debian changelog](https://github.com/precice/precice/blob/develop/tools/releasing/packaging/debian/changelog)
   * [ ] (prepare independent release) [Python bindings](https://github.com/precice/python-bindings)
   * [ ] (prepare independent release, if necessary!) [MATLAB bindings](https://github.com/precice/matlab-bindings)
* [x] Commit the version bump
* [x] Do regression tests using the release branch (specific revision) _list below :arrow_down:_ (all)
* [x] Fix potential problems in develop (all)
* [ ] Draft message to mailing list
* [x] Update documentation (all)
  * [x] Update markdown configuration reference in wiki
* [x] Approve the PR with at least two reviews (all)
* [x] Merge PR to master ( use `git merge --no-ff release-N` )
* [x] Tag release on master `vN` and verify by running `git describe --tags`
* [ ] Merge back to develop and verify by running `git describe --tags`
* [ ] Push master and push the `vN` tag
* [ ] [Draft a new release on GitHub](https://github.com/precice/precice/releases/new)
* [ ] Generate packages and upload to the draft release
   * [ ] Latest Ubuntu LTS
   * [ ] Latest Ubuntu
* [ ] Publish the GitHub release

## Regression Tests

Run all these tests manually on your system. If you succeed, please write a comment with the revisions of the components that you used below. Example: https://github.com/precice/precice/pull/507#issuecomment-530432289 and update the table.

| State | Success | Failure | Skipped |
| --- | --- | --- | --- |
| Write | `:o:` | `:x:` | `:fast_forward:` |
| Read | :o: | :x: | :fast_forward: |

| State | Tester | Test |
| --- | --- | --- |
| :o: | @MakisH    | SU2 / CalculiX [flap_perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/SU2-CalculiX) |
| :o: | @MakisH | OpenFOAM / OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) |
| :o: | @MakisH | OpenFOAM / OpenFOAM - NP mapping in OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) |
| :o: | @KyleDavisSA  | OpenFOAM / CalculiX FSI [flap perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/OpenFOAM-CalculiX) |
| :o: | @KyleDavisSA  | OpenFOAM / CalculiX FSI - NP mapping in CalculiX [3D_Tube](https://github.com/precice/tutorials/tree/develop/FSI/3D_Tube/OpenFOAM-CalculiX) |
| :o: | @KyleDavisSA  | OpenFOAM / CalculiX / OpenFOAM CHT [heat_exchanger](https://github.com/precice/tutorials/tree/develop/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX) |
| :fast_forward:  | @MakisH | OpenFOAM / deal.II [FSI cylinderFlap](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap_2D/OpenFOAM-deal.II) |
| :fast_forward:  | @MakisH | OpenFOAM / deal.II [FSI cylinderFlap_2D](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap_2D/OpenFOAM-deal.II) |
| :o: | @MakisH | OpenFOAM / deal.II [flap_perp_2D](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp_2D/OpenFOAM-deal.II) |
| :o: | @MakisH | OpenFOAM / deal.II [flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-deal.II) |
| :o: | @BenjaminRueth  | OpenFOAM / FEniCS [flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-FEniCS) |
| :o: | @BenjaminRueth | OpenFOAM / FEniCS [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) |
| :o: | @BenjaminRueth | OpenFOAM / FEniCS [cylinderFlap, only run first few minutes](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap/OpenFOAM-FEniCS) |
| :o:| @uekerman   | OpenFOAM / Nutils [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils) |
| :o: | @BenjaminRueth | FEniCS / FEniCS [partitioned-heat](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) |
| :o: | @IshaanDesai  | MATLAB / MATLAB [ODEs](https://github.com/precice/matlab-bindings/tree/develop/tutorial) |
| :o: | @uekerman | Alya |
| :o: | @uekerman | 1D-ElasticTube [C++](https://github.com/precice/elastictube1d/tree/develop/cxx) | 
| :o: | @BenjaminRueth  | 1D-ElasticTube [Python](https://github.com/precice/elastictube1d/tree/develop/python) |
| :o: | @atotoun | SuperMUC Ateles / Ateles |
| :o: | @KyleDavisSA | Solverdummy [Fortran 2003](https://github.com/precice/precice/tree/develop/tools/solverdummies/f2003) | 
| :o: | @BenjaminRueth  | Solverdummy [Python](https://github.com/precice/python-bindings/tree/develop/solverdummy) |
| :o: | @IshaanDesai  | Solverdummy [MATLAB](https://github.com/precice/matlab-bindings/tree/develop/solverdummy) |

## Post-release

* [ ] Update Arch Linux AUR Package
* [ ] Update Spack recipe

### Release new version for bindings (to ensure compatibility with newest preCICE version)

- [ ] fortan-module?
- [ ] [MATLAB bindings](https://github.com/precice/matlab-bindings/compare/master...develop)
- [ ] [python bindings](https://github.com/precice/python-bindings/compare/master...develop)

### (only if breaking changes) Open PRs or issues `develop -> master` for all adapters

- [ ] athlet-adapter? 
- [ ] [calculix-adapter](https://github.com/precice/calculix-adapter/compare/master...develop)
- [ ] code_aster-adapter?
- [ ] [comsol-adapter](https://github.com/precice/comsol-adapter/compare/master...develop)
- [ ] [dealii-adapter](https://github.com/precice/dealii-adapter/compare/master...develop)
- [ ] lsdyna-adapter?
- [ ] [fenics-adapter](https://github.com/precice/fenics-adapter/compare/master...develop)
- [ ] [fluent-adapter](https://github.com/precice/fluent-adapter/compare/master...develop)
- [ ] mbdyn-adapter?
- [ ] [openfoam-adapter](https://github.com/precice/openfoam-adapter/compare/master...develop)
- [ ] [su2-adapter](https://github.com/precice/su2-adapter/compare/master...develop)

### (only if breaking changes) Open PRs or issues `develop -> master` for all other tools

- [ ] [aste](https://github.com/precice/aste/compare/master...develop)
- [ ] [elastictube1d](https://github.com/precice/elastictube1d/compare/master...develop)
- [ ] [tutorials](https://github.com/precice/tutorials/compare/master...develop)
- [ ] [systemtests](https://github.com/precice/systemtests/compare/master...develop)

### Marketing

* [ ] Send email and do marketing
* [ ] Tweet

### Misc

* [ ] Update the [PR template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md)

### CODE REVIEW

**Comment by MakisH** [comment]
:x: The FSI/cylinderFlap_2D/OpenFOAM-deal.II [fails with an IQN-related error](https://github.com/precice/tutorials/issues/94).

**Comment by BenjaminRueth** [comment]
:o: Solverdummy Python works.

**Comment by BenjaminRueth** [comment]
:o: 1D-ElasticTube Python works.

**Comment by BenjaminRueth** [comment]
:o: FEniCS / FEniCS partitioned-heat works.

**Comment by uekerman** [comment]
:o: Alya Flap works, [Alya version](https://gitlab.lrz.de/uekerman/alya_small/-/commit/e7a767cd4cb1d3c37a7ef2afe247532715ff97a6)

**Comment by uekerman** [comment]
:o: Elastic Tube C++ works, https://github.com/precice/elastictube1d/pull/34/commits/541ae69580b682a6aa6231f68046fdb0fd02d607

**Comment by BenjaminRueth** [comment]
:o: OpenFOAM / FEniCS flow-over-plate works.

**Comment by MakisH** [comment]
Missing in the Changelog:
- Added new check for watchpoint dimensions (if somebody has a 3D watchpoint defined on a 2D interface, it will complain)
- Added new check for defining the watchpoint on a provided mesh.

**Comment by BenjaminRueth** [comment]
:x: OpenFOAM / FEniCS flap_perp breaks. Problem with change introduced in https://github.com/precice/tutorials/commit/29627814d4e8ae4811f69a2015d88a57ca12725b#diff-8bf6de024f53a446473d6dd147906b4aL35-R41

**Comment by BenjaminRueth** [comment]
:o: OpenFOAM / FEniCS works. https://github.com/precice/python-bindings/commit/6781436a36cdb60be78ccb12d7232607db43ad92 https://github.com/precice/fenics-adapter/commit/305fd066f35eb48ae360fbdd474aef1b57ac37eb https://github.com/precice/tutorials/commit/29627814d4e8ae4811f69a2015d88a57ca12725b https://github.com/precice/openfoam-adapter/commit/d9b3ac444e193f592f59af00b56d24f48b2f3759 (OF6)

**Comment by uekerman** [comment]
:o: OpenFOAM-Nutils works, latest Nutils commit: https://github.com/evalf/nutils/commit/cfe155b3a7ee4a4ead0fe04354aac2665779161d, Python bindings: https://github.com/precice/python-bindings/tree/v2.1.0.1rc2

**Comment by KyleDavisSA** [comment]
:o:  OpenFOAM / CalculiX FSI flap perp works. Latest tutorials https://github.com/precice/tutorials/commit/bf30b5a2bb35f948a5a07a3c1ebccd18ae9e8009, and Calculix https://github.com/precice/calculix-adapter/commit/9291228adf67e8b57d0bbf3ec2aa67a58fd1edcb

**Comment by KyleDavisSA** [comment]
:o: OpenFOAM / CalculiX FSI - NP mapping in CalculiX 3D_Tube works (only ran a few time windows. https://github.com/precice/tutorials/commit/bf30b5a2bb35f948a5a07a3c1ebccd18ae9e8009 and https://github.com/precice/calculix-adapter/commit/9291228adf67e8b57d0bbf3ec2aa67a58fd1edcb

**Comment by fsimonis** [comment]
The new spack package works with the latest dependencies.

**Comment by BenjaminRueth** [comment]
> x OpenFOAM / FEniCS flap_perp breaks. [precice/python-bindings@6781436](https://github.com/precice/python-bindings/commit/6781436a36cdb60be78ccb12d7232607db43ad92) [precice/fenics-adapter@305fd06](https://github.com/precice/fenics-adapter/commit/305fd066f35eb48ae360fbdd474aef1b57ac37eb) [precice/tutorials@2962781](https://github.com/precice/tutorials/commit/29627814d4e8ae4811f69a2015d88a57ca12725b) [precice/openfoam-adapter@d9b3ac4](https://github.com/precice/openfoam-adapter/commit/d9b3ac444e193f592f59af00b56d24f48b2f3759) (OF6)
> 
> Problem with change introduced in [precice/tutorials@2962781#diff-8bf6de024f53a446473d6dd147906b4aL35-R41](https://github.com/precice/tutorials/commit/29627814d4e8ae4811f69a2015d88a57ca12725b#diff-8bf6de024f53a446473d6dd147906b4aL35-R41)

False alarm. My local config was not up-to-date.

:o: OpenFOAM / FEniCS flap_perp breaks. https://github.com/precice/python-bindings/commit/6781436a36cdb60be78ccb12d7232607db43ad92 https://github.com/precice/fenics-adapter/commit/305fd066f35eb48ae360fbdd474aef1b57ac37eb https://github.com/precice/tutorials/commit/bf30b5a2bb35f948a5a07a3c1ebccd18ae9e8009 https://github.com/precice/openfoam-adapter/commit/d9b3ac444e193f592f59af00b56d24f48b2f3759 (OF6)

**Comment by uekerman** [comment]
> x The FSI/cylinderFlap_2D/OpenFOAM-deal.II [fails with an IQN-related error](https://github.com/precice/tutorials/issues/94).

:o: The problem is not due to preCICE, but due to a false tutorial setup that we are anyway already working on. No alarm.

**Comment by KyleDavisSA** [comment]
:o: OpenFOAM / CalculiX / OpenFOAM CHT heat_exchanger works. precice/tutorials@bf30b5a and precice/calculix-adapter@9291228

**Comment by KyleDavisSA** [comment]
:o: Solverdummy Fortran 2003 works

**Comment by IshaanDesai** [comment]
:o: MATLAB - MATLAB ODE tutorial explicit and implicit cases work with: https://github.com/precice/matlab-bindings/commit/2c55a77a19226399dfdd422df98642820ae67bd4 and https://github.com/precice/precice/commit/d22ae5d4be4afebde0035fa83bb9c8400ec1ea89

**Comment by MakisH** [comment]
OpenFOAM-OpenFOAM flow-over-plate works:
- :o: nearest-neighbor works in serial
- :o: nearest-projection works in serial

OpenFOAM-deal.II (all tests in serial):
- flap_perp  (until t>=0.1)
   - :o: flap_perp linear works
   - :o: flap_perp nonlinear works
   - :o: flap_perp_2D linear works
   - :o: flap_perp_2D nonlinear works
- cylinderFlap (until t>=0.004)
   - :o: cylinderFlap linear  works
   - :x: cylinderFlap nonlinear fails with RBF error after the second time window (t=0.004) (*)
   - :x: cylinderFlap_2D linear explodes later (**)
   - :x: cylinderFlap_2D nonlinear fails similarly to 3D case

<details><summary>*: cylinderFlap nonlinear (maybe not a new error): (...)</summary>

```
---[precice]  Mapping Stress consistent from Fluid-Mesh-Centers (ID 0) to Solid_mesh (ID 2) for dimension 2) with polynomial set to separate
KSP Object: Coefficient Solver (solverC_) 1 MPI processes
  type: gmres
    restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    happy breakdown tolerance 1e-30
  maximum iterations=10000, nonzero initial guess
  tolerances:  relative=1e-09, absolute=1e-50, divergence=10000.
  left preconditioning
  using PRECONDITIONED norm type for convergence test
PC Object: (solverC_) 1 MPI processes
  type: icc
    out-of-place factorization
    0 levels of fill
    tolerance for zero pivot 2.22045e-14
    using Manteuffel shift [POSITIVE_DEFINITE]
    matrix ordering: natural
    factor fill ratio given 1., needed 1.
      Factored matrix follows:
        Mat Object: 1 MPI processes
          type: seqsbaij
          rows=90, cols=90
          package used to perform factorization: petsc
          total: nonzeros=4095, allocated nonzeros=4095
          total number of mallocs used during MatSetValues calls=0
              block size is 1
  linear system matrix = precond matrix:
  Mat Object: C 1 MPI processes
    type: seqsbaij
    rows=90, cols=90
    total: nonzeros=4095, allocated nonzeros=4095
    total number of mallocs used during MatSetValues calls=0
        block size is 1
---[precice] ERROR:  The linear system of the RBF mapping from mesh Fluid-Mesh-Centers to mesh Solid_mesh has not converged. This means most probably that the mapping problem is not well-posed. Please check if your coupling meshes are correct. Maybe you need to fix axis-aligned mapping setups by marking perpendicular axes as dead?
```
It also cannot converge (see `precice-Solid-iterations.log`):
```
TimeWindow  TotalIterations  Iterations  Convergence  QNColumns  DeletedQNColumns  DroppedQNColumns  
1  100  100  0  3  96  0  
2  200  100  0  19  83  0 
```
</details>

<details><summary>**: cylinderFlap_2D linear: (...)</summary>

deal.II explodes without any error output:
```
Timestep 10 @ 0.020000s
	 Direct solver: 
	     No of iterations:	1
 	     Final residual:	0.000000
---[precice]  relative convergence measure: relative two-norm diff = 317.191, limit = 5e-05, normalization = 64783.8, conv = false
---[precice]  relative convergence measure: relative two-norm diff = 2.82029, limit = 5e-05, normalization = 0.284948, conv = false
---[precice]  Mapping Stress consistent from Fluid-Mesh-Centers (ID 0) to Solid_mesh (ID 2) for dimension 0) with polynomial set to separate
---[precice]  Mapping Stress consistent from Fluid-Mesh-Centers (ID 0) to Solid_mesh (ID 2) for dimension 1) with polynomial set to separate
---[precice]  it 3 of 100 | dt# 10 | t 0.018 of 15 | dt 0.002 | max dt 0.002 | ongoing yes | dt complete no | read-iteration-checkpoint | 

Timestep 10 @ 0.020000s
	 Direct solver: 
	     No of iterations:	1
 	     Final residual:	0.000000
     
```

`precice-Solid-iterations.log`:
```
TimeWindow  TotalIterations  Iterations  Convergence  QNColumns  DeletedQNColumns  DroppedQNColumns  
1  100  100  0  2  97  0  
2  200  100  0  13  88  0  
3  300  100  0  20  92  0  
4  339  39  1  41  17  0  
5  354  15  1  45  10  0  
6  372  18  1  48  14  0  
7  406  34  1  42  39  0  
8  506  100  0  31  110  0  
9  606  100  0  24  106  0  
```
</details>

Environment:
- preCICE v2.0.2-244-gd22ae5d
- OpenFOAM v2006
- OpenFOAM adapter `develop` https://github.com/precice/openfoam-adapter/commit/46c1dcffe2377f1d5ecd74b996746e8e65a6aee3
- deal.II 9.2.0
- deal.II adapter `develop` https://github.com/precice/dealii-adapter/commit/e6ff230dd213c0908820d72235e390e4dfbbacbe

**Comment by IshaanDesai** [comment]
:o: MATLAB Solverdummy works with: https://github.com/precice/matlab-bindings/commit/2c55a77a19226399dfdd422df98642820ae67bd4 and https://github.com/precice/precice/commit/d22ae5d4be4afebde0035fa83bb9c8400ec1ea89

**Comment by atotoun** [comment]
:o: Ateles-Ateles test case on SuperMUC-NG works.

**Comment by MakisH** [comment]
Post-release:
- The Fortran module hasy updated its solver dummy to add data transfer and is also using the renamed functions.
- We don't need to update anything in any adapter.
- The OpenFOAM adapter develop was merged to master.
- We don't need to update anything in the elastictube1d.
- The tutorials have been updated to accomodate new restrictions in respect of watchpoint dimensions, watchpoint on providing mesh. Merged to develop to master.

**Comment by uekerman** [comment]
@fsimonis Could you please add as TODO boxes under marketing
* send announcement to mailing list :o:
* CFD-Online
* NADigest

**Comment by BenjaminRueth** [comment]
> 
> 
> @fsimonis Could you please add as TODO boxes under marketing
> 
>     * send announcement to mailing list ⭕
> 
>     * CFD-Online
> 
>     * NADigest

I just created a PR with these changes for future releases: #838

**Comment by BenjaminRueth** [comment]
Matlab bindings are released: https://github.com/precice/matlab-bindings/pull/21#event-3575037798, https://github.com/precice/matlab-bindings/releases/tag/v2.1.0.1

**Pull request merged**
