### PR TITLE
Change reference paper in README to new v2 paper

### PR DESCRIPTION
**Pull request by IshaanDesai**
## Main changes of this PR

Updates the reference paper in the README to the newly released manuscript: https://doi.org/10.12688/openreseurope.14445.1

## Author's checklist

* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I ran `make format` to ensure everything is formatted correctly.
* [ ] I sticked to C++14 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Review by MakisH — APPROVED** [review]
Looks good, assuming that we already want to remove the 2016 paper, even though the new one is not reviewed yet.

**Comment by fsimonis** [comment]
Let's link to https://precice.org/publications instead.

**Comment by IshaanDesai** [comment]
@MakisH @fsimonis is it reasonable now? Basically we have offloaded the problem of which reference paper to refer to, to the website. But that is also okay I guess, lets handle it properly there.

**Comment by MakisH** [comment]
But now the link to the publications is duplicate. I would essentially remove the last sentence and only keep the link to the website.

**Comment by IshaanDesai** [comment]
> But now the link to the publications is duplicate. I would essentially remove the last sentence and only keep the link to the website.

Ah indeed! I did not see this at all. I'll just remove the last sentence then.

**Pull request merged**
