### PR TITLE
Release 3.1.0

### PR DESCRIPTION
**Pull request by fsimonis**
## How to work with this template

* [x] assign a release manager, who takes care of the process
* [ ] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Pre-PR steps

* [x] Look over [PRs](https://github.com/precice/precice/pulls?q=is%3Apr+no%3Amilestone+is%3Aclosed) and [Issues](https://github.com/precice/precice/issues?q=is%3Aissue+no%3Amilestone+is%3Aclosed) without an assigned version. (all)
* [x] Look over entries in [`docs/changelog`](https://github.com/precice/precice/blob/develop/docs/changelog)) (all)
   * Add missing entries, if necessary
   * Fix wording and tense
* [x] Make sure you have the latest `develop` and `main` branches locally.
* [ ] ~~Merge `main` to `develop` ( This should result in no commits )~~
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [x] Update the list of operating systems for the package generation in `.github/workflows/release.yml`
* [x] Create branch `release-vX.Y.Z` from develop. If needed, `git rebase develop`.
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version
* [x] Look over the updated `CHANGELOG.md` of the release branch (all)
   * Check for merged lines
   * Add things, if necessary
   * Fix wording and tense
   * Sort the entries lexicographically
   * Extract summary
* [x] Verify the version changes in:
   * [x] `CHANGELOG`
   * [x] `CMakeLists.txt`
   * [x] `tools/releasing/packaging/debian/changelog`
* [x] Commit the version bump
* [x] Push the release branch to the precice repository
* Prepare independent releases
   * [ ] [Python bindings](https://github.com/precice/python-bindings/blob/develop/docs/ReleaseGuide.md)
   * [ ] (if necessary!) [MATLAB bindings](https://github.com/precice/matlab-bindings/blob/develop/docs/ReleaseGuide.md)
   * [ ] (if necessary!) [JULIA bindings](https://github.com/precice/PreCICE.jl)

## Step by step guide

* [x] Open PR from `release-vX.Y.Z` to `main` (use [this template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/release_pull_request_template.md))
* [x] Do regression tests using the release branch (specific revision) _list below :arrow_down:_ (all)
* [x] Fix potential problems in develop (all)
* [x] Rebase the release branch on develop (all)
* [x] Commit the version bump
* [x] Update documentation (all)
   * [x] Update [XML configuration reference](https://github.com/precice/precice.github.io/blob/master/_includes/xmlreference.md)
   * [x] Update version in [precice/precice.github.io](https://github.com/precice/precice.github.io):
      * `_config.yml`
      * `_data/sidebars/docs_sidebar.yml`
* [x] Approve the PR with at least two reviews (all)
* [x] Merge PR to `main` ( use `git merge --no-ff release-vX.Y.Z` )
* [x] Tag release on `main` `vX.Y.Z` and verify by running `git describe --tags`
* [x] Merge back to `develop` and verify by running `git describe --tags`
* [ ] Triple check that you haven't messed anything up. (You can always discard local changes)
* [ ] Push `main` and push the `vX.Y.Z` tag
* [ ] Push `develop`
* [ ] Wait for the release pipeline
  * [ ] [To create a new draft release on GitHub](https://github.com/precice/precice/releases)
  * [ ] To automatically generate packages for the latest Debian and the two latest Ubuntu LTS versions.
* [ ] Write release text
* [ ] Publish the GitHub release

## Regression Tests

Use the following branches:
* precice `release-v3.1.0`
* pyprecice `python-bindings-v3.1.0.0`
* matlab-bindings `matlab-bindings-v3.1.0.0`
* rest `main`(`master`)

Run all these tests manually on your system. If you succeed, please write a comment with the revisions of the components that you used below. Example: https://github.com/precice/precice/pull/507#issuecomment-530432289 and update the table.

| State | Success | Failure | Skipped |
| --- | --- | --- | --- |
| Write | `:o:` | `:x:` | `:fast_forward:` |
| Read | :o: | :x: | :fast_forward: |

| State | Tester | Test |
| --- | --- | --- |
| :o: | @MakisH  | [quickstart](https://github.com/precice/tutorials/tree/master/quickstart) fluid-openfoam - solid-cpp |
| :o: | @MakisH | flow-over-heated-plate _all_ |
| :o: | @MakisH | [perpendicular-flap](https://github.com/precice/tutorials/tree/master/perpendicular-flap) fluid-openfoam - solid-dune |
| :o: | @MakisH | [perpendicular-flap](https://github.com/precice/tutorials/tree/master/perpendicular-flap) fluid-nutils - solid-calculix |
| :o: | @MakisH | [perpendicular-flap](https://github.com/precice/tutorials/tree/master/perpendicular-flap) fluid-openfoam - solid-dealii |
| :o: | @MakisH | [perpendicular-flap](https://github.com/precice/tutorials/tree/master/perpendicular-flap) fluid-su2 - solid-fenics |
| :o: | @fsimonis | [heat-exchanger-simplified](https://github.com/precice/tutorials/tree/master/heat-exchanger-simplified) fluid-(bottom+top)-openfoam - solid-calculix |
| :o: | @IshaanDesai | two-scale-heat-conduction macro-nutils - micro-nutils |
| :o: | #1984 | [elastic-tube-1d](https://github.com/precice/tutorials/tree/master/elastic-tube-1d) fluid-cpp - solid-python |
| :o: | @MakisH https://github.com/precice/tutorials/pull/509 | [elastic-tube-3d](https://github.com/precice/tutorials/tree/master/elastic-tube-3d) fluid-openfoam - solid-calculix |
| :o: | @uekerman | breaking-dam-2d fluid-openfoam - solid-calculix |
| :o: | @fsimonis | flow-around-controlled-moving-cylinder controller-fmi - fluid-openfoam |

## Post-release

* [ ] Update version specific documentation
* [ ] Flag [Arch Linux AUR package](https://aur.archlinux.org/packages/precice) and dependants as out-of-date.
* [ ] Update Spack recipe
* [ ] Update `pyprecice` Spack
* [ ] Update Website:
    * [ ] Bump version in [`_config.yml`](https://github.com/precice/precice.github.io/blob/master/_config.yml)
    * [ ] Update the [XML reference](https://github.com/precice/precice.github.io/blob/master/_includes/xmlreference.md) using `binprecice md`
    * [ ] Look over the [Roadmap](https://www.precice.org/fundamentals-roadmap.html) and update entries.

### Release new version for bindings (to ensure compatibility with newest preCICE version)

- [ ] [Fortran module](https://github.com/precice/fortran-module/compare/master...develop)
- [ ] [MATLAB bindings](https://github.com/precice/matlab-bindings/blob/develop/docs/ReleaseGuide.md)
- [ ] [python bindings](https://github.com/precice/python-bindings/blob/develop/docs/ReleaseGuide.md)
- [ ] [Julia bindings](https://github.com/precice/PreCICE.jl)

### Marketing

This will be included into the marketing of the distribution.

### Misc

* [ ] Update the [PR template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/release_pull_request_template.md)

To open a new PR with this template, use this [PR template query](https://github.com/precice/precice/compare/new?template=release_pull_request_template.md)

### CODE REVIEW

**Comment by fsimonis** [comment]
We already did a pretty extensive testing of the `elastic-tube-1d` in #1984. The `elastic-tube-1d` for example took overall less iterations compared to v3.0.0.

The improved numerical accuracy may impact other tutorials too.

**Comment by MakisH** [comment]
In the perpendicular-flap, the watchpoint plots look macroscopically the same for OpenFOAM-CalculiX and SU2-deal.II:

watchpoints-openfoam-calculix

watchpoints-su2-dealii

They still differ in the last digits, though. For example, for OpenFOAM-CalculiX:

```diff
  Time  Coordinate0  Coordinate1  Displacement0  Displacement1  Force0  Force1
- 1.00000000e-02   0.00000000e+00   1.00000000e+00   1.40208926e-03   2.53734422e-06   2.03655843e+01  -1.52019984e+01
- 5.00000000e+00   0.00000000e+00   1.00000000e+00   4.74162578e-02   7.18069885e-05   7.15678920e+00   1.30275199e+01
+ 1.00000000e-02   0.00000000e+00   1.00000000e+00   1.40209082e-03   2.53740150e-06   2.03655856e+01  -1.52020001e+01
+ 5.00000000e+00   0.00000000e+00   1.00000000e+00   4.74080199e-02   7.18246368e-05   7.15671092e+00   1.30274986e+01
```

[openfoam-calculix-v3.0.0.log](https://github.com/precice/precice/files/14833216/openfoam-calculix-v3.0.0.log)
[openfoam-calculix-v3.1.0.log](https://github.com/precice/precice/files/14833217/openfoam-calculix-v3.1.0.log)
[su2-dealii-v3.0.0.log](https://github.com/precice/precice/files/14833221/su2-dealii-v3.0.0.log)
[su2-dealii-v3.1.0.log](https://github.com/precice/precice/files/14833222/su2-dealii-v3.1.0.log)

**Comment by MakisH** [comment]
More perpendicular-flap tests in https://github.com/precice/tutorials/pull/507

**Comment by MakisH** [comment]
Some results for elastic-tube-3d: https://github.com/precice/tutorials/pull/509

I don't have results with v3.0.0 or v2.5.0, besides the watchpoint plot in the tutorial.

**Comment by uekerman** [comment]
`breaking-dam-2d` runs and looks meaningful.

- openfoam adapter v1.3.0
- calculix adapter 2b5802e
- tutorials: 3485e524

**Comment by fsimonis** [comment]
`flow-around-controlled-moving-cylinder` works

image

image

image

image

**Comment by fsimonis** [comment]
The heat-exchanger-simplified works https://github.com/precice/tutorials/pull/513

**Review by IshaanDesai — APPROVED** [review]

**Review by uekerman — APPROVED** [review]

**Pull request merged**
