### PR TITLE
Release v3.1.1

### PR DESCRIPTION
**Pull request by fsimonis**
## How to work with this template

* [x] assign a release manager, who takes care of the process
* [ ] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Pre-PR steps

* [x] Make sure you have the latest `main` branch locally.
* [x] Create branch `hotfix-v3.1.1` from ~~`main`. If needed, `git rebase main`.~~ _directly from develop_
* [x] Commit fixes to the hotfix branch
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [x] Update the list of operating systems for the package generation in `.github/workflows/release.yml`
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version
* [x] Look over the updated `CHANGELOG.md` of the hotfix branch (all)
   * Check for merged lines
   * Add things, if necessary
   * Fix wording and tense
   * Sort the entries lexicographically
   * Extract summary
* [x] Verify the version changes in:
   * [x] `CHANGELOG`
   * [x] `CMakeLists.txt`
   * [x] `tools/releasing/packaging/debian/changelog`
* [x] Commit the version bump
* [x] Push the hotfix branch to the precice repository

## Step by step guide

* [x] Open PR from `hotfix-v3.1.1` to `main` (use [this template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md))
* [x] ~~Do regression tests using the hotfix branch (specific revision)~~ (all)
* [x] Fix potential problems on the hotfix branch (all)
* [x] Reorder the commits for the version bump to be the latest. `git rebase -i main`
* [x] Approve the PR with at least two reviews (all)
* [ ] Merge PR to `main` ( use `git merge --no-ff hotfix-vX.Y.Z` )
* [ ] Tag hotfix on `main` `vX.Y.Z` and verify by running `git describe --tags`
* [ ] Merge `main` back to `develop` and verify by running `git describe --tags`
* [ ] Triple check that you haven't messed anything up. (You can always discard local changes)
* [ ] Push `main` and push the `vX.Y.Z` tag
* [ ] Push `develop`
* [ ] Wait for the release pipeline
  * [ ] [To create a new draft hotfix on GitHub](https://github.com/precice/precice/releases)
  * [ ] To automatically generate packages for the latest Debian and the two latest Ubuntu LTS versions.
* [ ] Write hotfix text
* [ ] Publish the GitHub hotfix

## Regression Tests

:fast_forward: _skipped_ :fast_forward: 

## Post-release

* [ ] Update version specific documentation
* [ ] Flag [Arch Linux AUR package](https://aur.archlinux.org/packages/precice) and dependants as out-of-date.
* [ ] Update Spack recipe
* [ ] Update `pyprecice` Spack
* [ ] Update Website:
    * [ ] Bump version in [`_config.yml`](https://github.com/precice/precice.github.io/blob/master/_config.yml)
    * [ ] Update the [XML reference](https://github.com/precice/precice.github.io/blob/master/_includes/xmlreference.md) using `binprecice md`
    * [ ] Look over the [Roadmap](https://www.precice.org/fundamentals-roadmap.html) and update entries.

### Release new version for bindings (to ensure compatibility with newest preCICE version)

_none_

### Marketing

_This will be done as part of the distribution release_

### Misc

* [ ] Update the [PR template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md)

To open a new PR with this template, use this [PR template query](https://github.com/precice/precice/compare/new?template=hotfix_pull_request_template.md)

### CODE REVIEW

**Review by davidscn — APPROVED** [review]

**Review by carme-hp — APPROVED** [review]

**Review by IshaanDesai — APPROVED** [review]

**Comment by MakisH** [comment]
Changelog looks good, I triggered the system tests: https://github.com/precice/tutorials/actions/runs/8661940055

**Comment by fsimonis** [comment]
Looks fishy. The elastic-tube-1d case runs in 10s on my machine™.

**Comment by uekerman** [comment]
> Looks fishy. The elastic-tube-1d case runs in 10s on my machine™ with precice and tutorials on develop.

For the systemstest, it's 12s. You probably read the wrong column?

If we compare to v3.0.0, the diff is probably still the timestep diff. We also observed this for v3.1.0.

**Comment by fsimonis** [comment]
True, so we go ahead.

**Review by MakisH — APPROVED** [review]

**Pull request merged**
