### PR TITLE
Moving mpi4py into bindings

### PR DESCRIPTION
**Pull request by BenjaminRueth**
Adds `mpi4py` as dependency for all cases. This PR is related to #311 and #300

### CODE REVIEW

**Comment by BenjaminRueth** [comment]
We should first merge #304

**Comment by fsimonis** [comment]
I am still unsure if this is the right way to go. This will require the user to install mpi even if precice does not use it.
It is less work for us, but questionable from the user perspective.

**Comment by MakisH** [comment]
> This will require the user to install mpi even if precice does not use it.

This seems to be enough for a "not the right way to go". What would be the advantages?

**Comment by uekerman** [comment]
See comments in https://github.com/precice/precice/issues/311
I don't think that there is a user that builds precice without mpi, but uses the python bindings. Which solver would that be? All this can be solved yes, I just think that there are just more important work packages we should spend our time with. If a user complains at some point we can still add the API function. But if there is a majority who sees this differently, I am happy to be overruled :)

**Comment by fsimonis** [comment]
I see three solutions:
1) Always init via mpi4py in our bindings, forcing MPI on the user.
2) Conditionally init via mpi4py by probing the preCICE API. This leads to a weird "maybe" dependency of mpi4py and forces us to extend the preCICE API.
2) Ask the user to import it if he compiled preCICE with MPI which will lead to problems.

Maybe we should tie this decision to the fact that we (aim to) provide packages with MPI compiled by default. Thus it make sense to stay consistent with that and put the MPI init into the bindings.

The aim should be that the following would be possible at some time:
```
$ sudo apt-get install precice
$ pip3 install --user precice
```

@uekerman Is there actually _a_ user using preCICE without mpi?

**Comment by BenjaminRueth** [comment]
This decision is related to the build process of the python bindings, therefore let's postpone the decision to a future release.

**Comment by BenjaminRueth** [comment]
I created an issue https://github.com/precice/python-bindings/issues/8 in our new repository for the bindings. Let's try to find an appropriate solution there.

**Pull request closed without merging**
