### PR TITLE
Move script createChangelog to tools/releasing

### PR DESCRIPTION
**Pull request by MakisH**
## Main changes of this PR

Moves the script `tools/building/createChangelog` to `tools/releasing/create-changelog`.

Also updates the respective `README.md` files and `CONTRIBUTING.md`. There is no mention of this tool in our website-based documentation.

## Motivation and additional information

It is a bit weird to have this in `tools/building`, as we only need it when releasing. I also got confused when looking for it.

## Author's checklist

* [x] I added a changelog file with this PR number in `docs/changelog/` if there are noteworthy changes. --> Not user-facing, no changelog.
* [x] I ran `tools/formatting/check-format` and everything is formatted correctly. --> Only Markdown files changed.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Do we need to update anything else? @fsimonis

### CODE REVIEW

**Review by fsimonis — CHANGES_REQUESTED** [review]
`createChangelog` creates a file `docs/changelog/N.md`, where N is the PR number on GitHub.
So this is used for most PRs.

The script that merges theses fragments is part of `tools/releasing/bumpversion.sh`.

**Comment by MakisH** [comment]
I am not sure I understand what you suggest to change, though. I thought we discussed this a while ago and decided that it is strange to have it in `building`. Other than that, I only change the naming style for consistency.

**Comment by fsimonis** [comment]
> It is a bit weird to have this in tools/building, as we only need it when releasing. I also got confused when looking for it.

We need it for PR authors to create their changelog fragment. The script is not required during a release.

> I thought we discussed this a while ago and decided that it is strange to have it in building.

I meant that it doesn't really fit into any of our current categories. Do we even need a subfolder for it?

**Comment by MakisH** [comment]
We could also move it to just `tools/`, then. But anyway, details, we can also just close this.

**Comment by fsimonis** [comment]
Sure

**Pull request closed without merging**
