### PR TITLE
CONFIG: add simple cmake install stage (issues #129)

### PR DESCRIPTION
**Pull request by olesenm**
- just the executable and library at the moment

### CODE REVIEW

**Comment by olesenm** [comment]
With installation of include files. If this can be merged and tested, it could be used to tag a new release or minor version which the spack packages could use. Or leave as a develop version within spack, which would also be OK.

**Comment by floli** [comment]
I have modified your install rules a bit.
If there no objections, I will merge tomorrow or after the weekend.

Thanks a lot for your contribution!

**Comment by olesenm** [comment]
+1

will you issue a new github release too? Then I can finish up the spack bits and get a merge request do there too.

**Comment by floli** [comment]
We will probably release beginning of August. Our release procedure is not very agile yet ;-)

**Comment by olesenm** [comment]
Ok, then we'll just leave spack as develop version only, which isn't so terrible either. Just need a merge into develop for that.

**Comment by olesenm** [comment]
The travis problem doesn't look like anything from me.

- BTW: both spack packages are now merged in.

**Pull request merged**
