### PR TITLE
Rename SolverInterface class

### PR DESCRIPTION
**Pull request by MakisH**
## Main changes of this PR

- [x] Renames the class `SolverInterface` to `Participant` in the C++ API
- [x] Renames the files `SolverInterface.xpp` to `Participant.xpp`
- [x] Renames `SolverInterfaceImpl` to `ParticipantImpl`
- [x] Renames the files `SolverInterfaceImpl.xpp` to `ParticipantImpl.xpp`
- [x] Applies the same changes in the C bindings (file: `ParticipantC.h`)
- [x] Applies the same changes in the Fortran bindings (file: `ParticipantFortran.hpp`)
- ~~Renames `SolverInterfaceConfiguration` to ?? + files~~ -> suggestion: skip for now
- ~~Reorder `sources.cmake`~~ -> already not strictly ordered
- Does not yet introduce the central `precice.hpp` file -> All user-facing changes should end up there
- Does not yet modify the XML configuration and keeps the `SolverInterfaceConfiguration` class for now

## Motivation and additional information

As discussed in #1458, we want to rename the main API class from `SolverInterface` to `Participant`, as the name is more descriptive.

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* I added a changelog file with `make changelog` if there are user-observable changes since the last release. -> User-facing changes from this PR will be overwritten when introducing a global `precice.hpp`.
* I added a test to cover the proposed changes in our test suite. -> N/A
* For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html). -> Should happen when introducing a central `precice.hpp` and renaming the bindings files.
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [x] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by MakisH** [comment]
What would a good name be for `SolverInterfaceConfiguration`? `ParticipantConfiguration` is already taken, and covers the XML tag `<participant>`.

I would prefer to not change everything in a giant PR, so I would like again (similarly to the closed #1627) to not yet remove the `<solver-interface>` tag and do that separately, to keep things easier to review.

I suggest keeping it as-is in this PR, remove when dropping the `<solver-interface>` tag.

**Review by fsimonis — APPROVED** [review]
> I suggest keeping it as-is in this PR, remove when dropping the <solver-interface> tag.

Definitely a good idea. It will disappear anyhow.

Only thing that could also be done in a different PR is to rename the variable used for the Participant in the solverdummies. They currently use `interface`.

I already find the interface way easier to read! :+1:

**Comment by MakisH** [comment]
@fsimonis I merged `develop`. Could you please check for any renaming mentions of solver interface that are not stemming from the XML configuration?

**Comment by MakisH** [comment]
Follow-up regarding the central header file: https://github.com/precice/precice/pull/1643

**Comment by kanishkbh** [comment]
I noticed the copydoc lines still say `SolverInterface::<foo>`, which can now be changed to `Participant::<foo>`

**Comment by MakisH** [comment]
> I noticed the copydoc lines still say `SolverInterface::<foo>`, which can now be changed to `Participant::<foo>`

Thanks! I thought I changed it, but it probably got lost in one of the conflict resolutions. I will update it.

**Pull request merged**
