### PR TITLE
Fix acceleration for waveform iterations

### PR DESCRIPTION
**Pull request by NiklasKotarsky**
## Main changes of this PR

Draft to solve issue  #1696 built upon #1523 . 
Ensures that the acceleration is applied to every timestep in the waveform for both QN acceleration and relaxation. 

## Motivation and additional information

Adds support for time adaptive waveform iterations by moving the interpolation to the time storage with fixed waveform order 1. 
Removes  the constant specifier for the variable extrapolationOrder in the time storage class in order to make the instance copyable.

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I sticked to C++17 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
This branch definitely needs some merging and rebasing. I will take care of moving everything that is related to constant relaxation to #1696 soon. Thanks for all the contributions!

**Review by BenjaminRodenberg — COMMENTED** [review]
I moved some code from here to #1696. Let's keep this PR until we have also migrated the Quasi-Newton based acceleration schemes, but first let's finalize #1696.

**Comment by BenjaminRodenberg** [comment]
@NiklasKotarsky A lot of things have changed on `develop` and this PR needs a synchronization to develop. Does it generally make sense to merge `develop` into this PR or rather just re-implement the (few?) changes from here on top of the current version of `develop`?

**Comment by NiklasKotarsky** [comment]
Yes, it would make more sense to re-implement the changes from this branch in a new branch. The QN acceleration here with waveform iterations would also greatly benefit from some refactoring and optimization. Is it a good idea to leave this branch open as reference? I am going to close it as soon as I have started working on a updated version of an updated version of the QN acceleration.

**Comment by BenjaminRodenberg** [comment]
> Is it a good idea to leave this branch open as reference?

Sure. Just leave it open until the new version is published. You can also close this PR now or later.

Btw: Added the `wontfix` label, because this branch will not be merged anymore.

**Comment by NiklasKotarsky** [comment]
Closed in favor of  #1834.

**Pull request closed without merging**
