### PR TITLE
Add bulk methods for setting Triangles and Edges

### LINKED ISSUE #465: Adding bulk versions for setMeshEdge, setMeshTriangle
The preCICE API offers methods to set mesh vertices, edges and triangles.

We currently provide bulk versions only for adding vertices. We should add bulk versions for all primitives.
Bulk functions allow us to sanitize the entire data once at the interface and thus offers great runtime benefits during mesh creation.

### Status

| Primitve | Singular | Bulk |
| --- | --- | --- |
| Vertex | `setMeshVertex`  | `setMeshVertices` |
| Edge | `setMeshEdge` | :x: | 
| Triangle | `setMeshTriangle` | :x: | 
| Quad | `setMeshQuad` |

There are also `XWidthEdges()` versions of these.

### setMeshEdges
`void setMeshEdges(int meshID, int size, int const * vertexIDs, int * edgeIDs)`

`vertexIDs` has to point to a range of `2*size` vertex ids in the format `e0A e0B e1A e1B ...`
`edgeIDs` has to point to a range of `size` edge ids. The function writes the resulting edge ids to it in the format `e0 e1 e2 ...`

### setMeshTriangles
`void setMeshTriangles(int meshID, int size, int const * edgeIDs)`

`edgeIDs` has to point to a range of `3*size` edge ids in the format `t0AB t0BC t0CA t1AB t1BC ...`

### setMeshQuads
`void setMeshQuads(int meshID, int size, int const * edgeIDs)`

`edgeIDs` has to point to a range of `4*size` edge ids in the format `t0AB t0BC t0CD q0DA q1AB q1BC ...`

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds bulk counterparts for `setMeshTriangle` and `setMeshEdge`.

Closes #465

Reviewers, please check the changes to the SolverInterface as well as the implementation especially in the server parts.

# TODO
* [ ] Add tests
* [ ] Extend bindings

### CODE REVIEW

**Comment by uekerman** [comment]
It was hard work to make all bindings consistent. I would not want to sacrifice that here. Could in principle also got into another PR, but should not be postponed to another release.   
* `c`  
* `f2003`  
* `fortran`  
* `PySolverInterface`  
* `python`  
* `python_future`

Furthermore, we need integration tests and binding tests (where possible, e.g. python).

**Comment by fsimonis** [comment]
We also need tests here.

**Comment by BenjaminRueth** [comment]
> It was hard work to make all bindings consistent. I would not want to sacrifice that here. Could in principle also got into another PR, but should not be postponed to another release.
> 
>     * `c`
> 
>     * `f2003`
> 
>     * `fortran`
> 
>     * `PySolverInterface`
> 
>     * `python`
> 
>     * `python_future`
> 
> 
> Furthermore, we need integration tests and binding tests (where possible, e.g. python).

Did we already decide on a strategy here?

1. add everything to this PR (-> more work in this PR)
2. add support for language bindings in a different PR (-> we should already open an issue, to make sure we do not forget it + make sure that it gets done in the same release like this PR)

For the python bindings I am happy to contribute, even though I would prefer to only update `python_future` and not add the new feature in the (deprecated) `python` bindings.

**Comment by uekerman** [comment]
We can do the bindings in a different PR, but the integration tests for the new methods, we should do here.

**Comment by fsimonis** [comment]
Conclusion:
* Not a must for 2.0.0
* Finish feature after #574 
* Extend all bindings
* Add a test

**Comment by fsimonis** [comment]
I am closing this in favour of a new go.

**Pull request closed without merging**
