### PR TITLE
Handle interrupts in communication

### LINKED ISSUE #1443: preCICE suspectedly fails to recover from EINTR
**Describe your setup**

Operating system (e.g. Linux distribution and version): _Debian bullseye_
preCICE Version: 2.5.0

Add the versions/commit hashes of further adapter and/or bindings.

**Describe the problem**
When a preCICE application receives a signal while it is waiting on a socket, both sides of the application die with the message `Receiving data from another participant (using sockets) failed with a system error: read: Interrupted system call. This often means that the other participant exited with an error (look there)`. This is presumably caused by preCICE handling EINTR as an unrecoverable error.

**Step To Reproduce**
1. Install the latest development version of Nutils (which uses bottombar 2)
2. Run the partitioned-heat-condition tutorial

**Expected behaviour**
The tutorial code is expected to run without problems.

**Additional context**
The reason that bottombar 2 is causing the code to fail is that it uses setitimer to update itself, which triggers SIGALRM at a set frequency. The previous version used signals only for window resizes via SIGWINCH, which is not triggered as often and therefore caused fewer issues (though we have long received reports of tmux reattach mysteriously killing applications). We are in the process of making point releases for bottombar that set the siginterrupt flag to false, which fixes the issue. Nonetheless, we thought it good to point out that this issue exists and that it could potentially be fixed on your side as well.

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR:
- Extends robustness of the socket communication, correctly handling interrupts
- Extends messages for all communication types, especially handling the remote participant crashing.
- Correctly handles failing async requests
- Adds error messages for async requests

## Motivation and additional information

Closes #1443

## Author's checklist

* [x] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [x] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by gertjanvanzwieten** [comment]
Today I finally managed to try out the branch and unfortunately the issue does not seem to be fixed, even though the error message changed from `Receiving data from another participant (using sockets) failed with a system error: read: Interrupted system call. This often mean
s that the other participant exited with an error (look there)` (both sides) to `Receiving data from another participant failed with a system error: Interrupted system call.` on one side and `Receiving data from another participant failed with a system error: End of file.` on the other. Tested with the partitioned-heat-conduction tutorial coupling nutils to nutils (development version) with bottombar 2.0.2 (which does not yet contain our siginterrupt fix). I can send you the Dockerfile if it's helpful.

**Comment by fsimonis** [comment]
@gertjanvanzwieten Thank you very much for the report!

In summary:
* There are still places where EINTR isn't handled correctly.
* The error messages are wrong. We need to handle Inter vs Intracomm as well as sending vs receiving.

**Comment by fsimonis** [comment]
Turns out that this is more difficult than I thought as this requires to shift abstraction layers regarding communication.

Unsolvable without major refactoring is a way of restarting asynchronous calls.

**Comment by fsimonis** [comment]
Closing for mentioned reasons

**Pull request closed without merging**
