### PR TITLE
Add sample duplication tests to bspline tests

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR adds sample duplication tests to the BSpline tests to help deciding how to proceed in #1788

## Motivation and additional information

See #1788

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I sticked to C++17 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

### CODE REVIEW

**Comment by fsimonis** [comment]
@NiklasKotarsky @BenjaminRodenberg Do you plan on integrating these tests or can the PR be closed?

**Comment by BenjaminRodenberg** [comment]
Hard for me to judge whether these tests are needed or not. @NiklasKotarsky could you review and merge, if you think these tests are useful?

**Comment by NiklasKotarsky** [comment]
I am not sure if this is the correct place for such a test, since the underlying waveform and spline changes when we duplicate the sample at the end. It is also not obvious to me which feature breaks and in what sense when the duplication tests fail. This is also tested on a higher level in #1788 together with the min-time-step tag making the connection more clear. Therefore I would suggest closing this pull request in favor of the test in #1788.

**Comment by fsimonis** [comment]
@NiklasKotarsky OK. I'll close this PR.
If you make assumptions on b-splines of a given shape, then testing them in the bsplinetests is the correct way to go though. This makes problems easier to find as setups are easier to understand and it cuts out all other problem sources.

**Pull request closed without merging**
