### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by fsimonis**
## How to work with this template

* [x] assign a release manager, who takes care of the process @fsimonis 
* [ ] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Step by step guide
* [x] Look over [`CHANGELOG.md`](https://github.com/precice/precice/blob/develop/CHANGELOG.md) (@fsimonis )
   * Add things, if necessary
   * Extract summary
   * Fix wording
   * Sort the entries lexicographically
* [x] Look over the [Roadmap](https://github.com/precice/precice/wiki/Roadmap) and update entries.
* [x] Merge master to develop (No commits after the release on master)
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [x] Create branch `release-N` from develop. If needed, `git rebase develop`.
* [x] Open PR from `release-N` to `master` (use [this template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md))
* [x] Do regression tests using the release branch (specific revision) _list below :arrow_down:_ (all)
* [x] Fix potential problems in develop (all)
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version @fsimonis 
* [x] Verify the version changes in: @fsimonis 
   * [x] [CHANGELOG](https://github.com/precice/precice/blob/develop/CHANGELOG.md)
   * [x] [CMakeLists.txt](https://github.com/precice/precice/blob/develop/CMakeLists.txt)
   * [x] [debian changelog](https://github.com/precice/precice/blob/develop/tools/releasing/packaging/debian/changelog)
   * [ ] (do independent release, if necessary!) [Python bindings](https://github.com/precice/python-bindings)
   * [ ] (do independent release, if necessary!) [MATLAB bindings](https://github.com/precice/matlab-bindings)
* [x] Draft message to mailing list @uekerman 
* [x] Update documentation (all)
  * [ ] Update markdown configuration reference in wiki
* [x] Approve the PR with at least two reviews (all)
* [ ] Merge PR to master @fsimonis 
* [ ] Tag release on master and verify by running `git describe --tags` (on GitHub, make sure to select the release branch as target) @fsimonis 
* [ ] Merge back to develop and verify by running `git describe --tags` @fsimonis 

## Regression Tests

Run all these tests manually on your system. If you succeed, please write a comment with the revisions of the components that you used below. Example: https://github.com/precice/precice/pull/507#issuecomment-530432289

* [x] SU2 / CalculiX [flap_perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/SU2-CalculiX) @BenjaminRueth 
* [x] OpenFOAM / OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) @MakisH 
* [x] OpenFOAM / OpenFOAM - NP mapping in OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) @MakisH 
* [x] OpenFOAM / CalculiX FSI [flap perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/OpenFOAM-CalculiX) @MakisH 
* [x] OpenFOAM / CalculiX FSI - NP mapping in CalculiX [3D_Tube](https://github.com/precice/tutorials/tree/develop/FSI/3D_Tube/OpenFOAM-CalculiX) @MakisH 
* [x] OpenFOAM / CalculiX / OpenFOAM CHT [heat_exchanger](https://github.com/precice/tutorials/tree/develop/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX) @KyleDavisSA
* [x] OpenFOAM / deal.II [flap_perp_2D](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp_2D/OpenFOAM-deal.II) @MakisH 
* [x] OpenFOAM / FEniCS [flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-FEniCS) @IshaanDesai 
* [x] OpenFOAM / FEniCS [cylinderFlap, only run first few minutes](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap/OpenFOAM-FEniCS) @IshaanDesai 
* [x] OpenFOAM / FEniCS [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) @IshaanDesai 
* [x] OpenFOAM / Nutils [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils) @uekerman 
* [x] FEniCS / FEniCS [partitioned-heat](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) @IshaanDesai 
* [x] MATLAB / MATLAB [ODEs](https://github.com/precice/matlab-bindings/tree/develop/tutorial) @BenjaminRueth 
* [x] ExaFSA: Ateles / FASTEST :warning: Adapters are not ready for 2.0 :warning: @atotoun 
* [x] Alya @uekerman 
* [x] 1D-ElasticTube [C++](https://github.com/precice/elastictube1d/tree/develop/cxx) @fsimonis 
* [x] 1D-ElasticTube [Python](https://github.com/precice/elastictube1d/tree/develop/python) @fsimonis  https://github.com/precice/elastictube1d/issues/29
* [x] SuperMUC @atotoun 
* [x] Solverdummy [C++](https://github.com/precice/precice/tree/develop/tools/solverdummies/cpp) @fsimonis 
* [x] Solverdummy [C](https://github.com/precice/precice/tree/develop/tools/solverdummies/c) @fsimonis 
* [x] Solverdummy [Fortran](https://github.com/precice/precice/tree/develop/tools/solverdummies/fortran) @MakisH 
* [x] Solverdummy [Fortran 2003](https://github.com/precice/precice/tree/develop/tools/solverdummies/f2003)
* [x] Solverdummy [Python](https://github.com/precice/python-bindings/tree/develop/solverdummy) @fsimonis https://github.com/precice/python-bindings/pull/32
* [x] Solverdummy [MATLAB](https://github.com/precice/matlab-bindings/tree/develop/solverdummy) @BenjaminRueth 

## Post-release
* [ ] Generate packages
   * [ ] Latest Ubuntu LTS
   * [ ] Latest Ubuntu
   * [ ] Arch Linux AUR Package
* [ ] Update Spack recipe
* [ ] Send email and do marketing
* [ ] Tweet
* [ ] Update the [PR template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md) @BenjaminRueth https://github.com/precice/precice/pull/659

### CODE REVIEW

**Comment by fsimonis** [comment]
* `Solverdummy` C is working
* `Solverdummy` C++ is working

**Comment by MakisH** [comment]
I will test OpenFOAM-CCX, OpenFOAM-deal.II, OpenFOAM-SU2, and both Fortran solver dummies locally.

**Comment by IshaanDesai** [comment]
* FEniCS / FEniCS [partitioned-heat](https://github.com/precice/tutorials/tree/develop/HT/partitioned-heat/fenics-fenics) tutorial works with `fenics-adapter` commit: https://github.com/precice/fenics-adapter/commit/7ddb62b471cc7af9046bc97a2de24473d84d99ab
* OpenFOAM / FEniCS [flow-over-plate](https://github.com/precice/tutorials/tree/develop/CHT/flow-over-plate/buoyantPimpleFoam-fenics) tutorial works with `fenics-adapter` commit: https://github.com/precice/fenics-adapter/commit/7ddb62b471cc7af9046bc97a2de24473d84d99ab and `openfoam-adapter` commit: https://github.com/precice/openfoam-adapter/commit/e3bae881d635bf7c46a597dc3462fb91532abb43

**Comment by MakisH** [comment]
The following tests are failing on Ubuntu 18.04:
```
precice.mapping.petrbf
precice.parallel
```
I assume this is just due to the broken PETSc Ubuntu package and OpenMPI.

Also, the following tests time out:
```
precice.action
precice.m2n.mpiports
```

**Comment by MakisH** [comment]
:warning:  `make package` now only produces the `.tar.gz` archive and the respective checksum, not the Debian package. @fsimonis did I miss some change?

**Comment by MakisH** [comment]
OpenFOAM-OpenFOAM flow_over_plate seems to work on Ubuntu 18.04 with preCICE installed from the Debian package, both in serial and in parallel. Visually, the results look reasonable.

Same for the nearest-projection variant.

**Comment by MakisH** [comment]
The bundled examples (C++, C, Fortran dummies) work like a charm! :tada:

The Fortran 2003 dummy also worked without any difficulty! :tada:

**Comment by MakisH** [comment]
The C++ elastictube1d worked like a charm. :rocket: 

I had trouble installing the python bindings. It was not as simple as `pip3 install --user .`: it could not find cython and after installing it it could not find other packages. `python3 setup.py install --user` also failed at finding numpy. Giving up for now @BenjaminRueth.

**Comment by MakisH** [comment]
Most of the wiki is now ported to v2. Still need to update:
- Changes related to https://github.com/precice/precice/pull/572
- `reused-timesteps-at-restart`
- Compare changelog with [porting guide](https://github.com/precice/precice/wiki/Porting-adapters-from-preCICE-1.x-to-2.x)

**Comment by uekerman** [comment]
Furthermore, there is:

* [ ] Adjust [logging examples](https://github.com/precice/precice/wiki/Logging-Configuration) to new INFO behavior
* [ ] Adjust adapter example to single step init https://github.com/precice/precice/pull/614
* [ ] Changed CMake Variables for enabling features https://github.com/precice/precice/pull/609
* [ ] CMake variables for enabling C and Fortran
* [ ] Renamed `export` configuration option `timestep-interval` to `every-n-time-windows`
* [ ] Action "on-timestep-complete-post" -> "on-time-window-complete-post" [action wiki](https://github.com/precice/precice/wiki/Actions-Configuration)
* [ ] Remove all traces of serial vs. parallel configuration tutorial descriptions

**Comment by BenjaminRueth** [comment]
matlab solverdummy and matlab-matlab tutorials work with https://github.com/precice/matlab-bindings/commit/bb6d82f72f12562a83308f89bd3ff0c4b70d9ea7

**Comment by uekerman** [comment]
Alya and OpenFOAM-Nutils CHT work

**Comment by BenjaminRueth** [comment]
su2 ccx tutorial works with

* su2 adapter revision https://github.com/precice/su2-adapter/commit/17c60318826df0d6a6129d35a42220c71a11ec3b
* ccx adapter revision https://github.com/precice/calculix-adapter/commit/505e90aa736c410da41bfd3578daa0bef7989f64
* tutorials revision https://github.com/precice/tutorials/commit/485cf69e888add40db2078a6e6d2e8a252482dba

**Comment by fsimonis** [comment]
I just rebased the release branch on develop after merging #658.
Test `precice.parallel` should succeed now.

**Comment by uekerman** [comment]
* [ ] We should also update the configuration explanation http://run.coplon.de/

**Comment by IshaanDesai** [comment]
OpenFOAM / FEniCS [flap_prep](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/OpenFOAM-FEniCS) works with https://github.com/precice/fenics-adapter/commit/7ddb62b471cc7af9046bc97a2de24473d84d99ab and https://github.com/precice/openfoam-adapter/commit/e3bae881d635bf7c46a597dc3462fb91532abb43 rebased on https://github.com/precice/openfoam-adapter/commit/5ed5e0dc540e680ee30ff10a6d19421558fd4f21 (I did this because I am using OpenFOAM 7)

**Comment by fsimonis** [comment]
Rebase after:
* after improving the log output #661 
* fixing `make test_install` (still pointed to `tools/solverdummies`)
* removed a copy of Logger in `PRECICE_TRACE`.

These are no critical issues, thus we can simply continue the testing.

**Comment by MakisH** [comment]
Also on Ubuntu 18.04 with preCICE installed from a Debian package:
- OpenFOAM / CalculiX FSI flap perp runs fine (all from develop), results look fine (quick visual check)
- OpenFOAM / CalculiX FSI cylinder-flap seems to run fine as well.
- OpenFOAM / CalculiX FSI - NP mapping in CalculiX 3D_Tube seems to run fine.

**Comment by MakisH** [comment]
With the latest state of `release-v2.0.0`, I still get a timeout for the `action` test and `failed` for the `parallel`. I am pretty sure that I running on a clean system, but I may need to check again.

**Comment by MakisH** [comment]
- OpenFOAM / deal.II flap_perp_2D runs successfully.

**Comment by MakisH** [comment]
- OpenFOAM / CalculiX / OpenFOAM CHT heat_exchanger: It still fails for me, as I am affected by https://github.com/precice/calculix-adapter/issues/27

**Comment by MakisH** [comment]
Wiki done for parallel. Elastictube1d also.

**Comment by MakisH** [comment]
>     * [ ]  We should also update the configuration explanation http://run.coplon.de/

I am taking care of this, but it can take a while. The CI seems to be broken (we have not touched it in a while). We can safely ignore this point for now.

**Comment by MakisH** [comment]
I tried again to run the tests on a clean (nothing installed) Ubuntu 18.04 image in a VM. The `action` still times out and `parallel` now succeeds.

Both Python 2.7 and 3.6 are installed.

**Comment by uekerman** [comment]
> I tried again to run the tests on a clean (nothing installed) Ubuntu 18.04 image in a VM. The `action` still times out and `parallel` now succeeds.
> 
> Both Python 2.7 and 3.6 are installed.

Do you know which test and where exactly it hangs?

**Comment by MakisH** [comment]
On my normal Ubuntu 16.04, `precice.action` succeeds.

On the clean Ubuntu 18.04 VM, `precice.action` fails with the following error (exporting `CTEST_OUTPUT_ON_FAILURE=ON`):

```
      Start  2: precice.action
 2/20 Test  #2: precice.action ...................***Timeout  20.03 sec
Test setup error: Running 6 test cases...
Test setup error: Test setup error: no test cases matching filter or all test cases were disabled
no test cases matching filter or all test cases were disabled
no test cases matching filter or all test cases were disabled
(0) 18:51:22 [action::PythonAction]:143 in initialize: ERROR: Could not load python module "TestAllAction" at path "/home/tester/precice/src/action/tests/"!
```

Interestingly, now every parallel test also timesout, while petrbf fails:
<details>
<summary>Click to see the log</summary>
<p>

```
      Start  4: precice.com.mpiports
 4/20 Test  #4: precice.com.mpiports .............***Timeout  20.02 sec
Running 5 test cases...
Running 5 test cases...
Running 5 test cases...
Running 5 test cases...

      Start  5: precice.cplscheme
 5/20 Test  #5: precice.cplscheme ................   Passed    6.32 sec
      Start  6: precice.io
 6/20 Test  #6: precice.io .......................   Passed    1.13 sec
      Start  7: precice.m2n
 7/20 Test  #7: precice.m2n ......................   Passed    1.82 sec
      Start  8: precice.m2n.mpiports
 8/20 Test  #8: precice.m2n.mpiports .............***Timeout  20.02 sec
Running 1 test case...
Running 1 test case...
Running 1 test case...
Running 1 test case...

      Start  9: precice.mapping
 9/20 Test  #9: precice.mapping ..................   Passed    0.51 sec
      Start 10: precice.mapping.petrbf
10/20 Test #10: precice.mapping.petrbf ...........***Failed    5.56 sec
Running 25 test cases...
Running 25 test cases...
Running 25 test cases...
Running 25 test cases...
(0) 18:52:40 [mapping::PetRadialBasisFctMapping]:572 in computeMapping: WARNING: RBF rescaling linear system has not converged. Deactivating rescaling!
(3) 18:52:40 [mapping::PetRadialBasisFctMapping]:572 in computeMapping: WARNING: RBF rescaling linear system has not converged. Deactivating rescaling!
(2) 18:52:40 [mapping::PetRadialBasisFctMapping]:572 in computeMapping: WARNING: RBF rescaling linear system has not converged. Deactivating rescaling!
(1) 18:52:40 [mapping::PetRadialBasisFctMapping]:572 in computeMapping: WARNING: RBF rescaling linear system has not converged. Deactivating rescaling!
KSP Object:Coefficient Solver(solverC_) 4 MPI processes
  type: gmres
    GMRES: restart=30, using Classical (unmodified) Gram-Schmidt Orthogonalization with no iterative refinement
    GMRES: happy breakdown tolerance 1e-30
  maximum iterations=10000
  tolerances:  relative=1e-09, absolute=1e-50, divergence=10000.
  left preconditioning
  using nonzero initial guess
  using PRECONDITIONED norm type for convergence test
PC Object:(solverC_) 4 MPI processes
  type: bjacobi
    block Jacobi: number of blocks = 4
    Local solve is same for all blocks, in the following KSP and PC objects:
  KSP Object:  (solverC_sub_)   1 MPI processes
    type: preonly
    maximum iterations=10000, initial guess is zero
    tolerances:  relative=1e-05, absolute=1e-50, divergence=10000.
    left preconditioning
    using NONE norm type for convergence test
  PC Object:  (solverC_sub_)   1 MPI processes
    type: icc
      0 levels of fill
      tolerance for zero pivot 2.22045e-14
      using Manteuffel shift [POSITIVE_DEFINITE]
      matrix ordering: natural
      factor fill ratio given 1., needed 1.
        Factored matrix follows:
          Mat Object:           1 MPI processes
            type: seqsbaij
            rows=2, cols=2
            package used to perform factorization: petsc
            total: nonzeros=3, allocated nonzeros=3
            total number of mallocs used during MatSetValues calls =0
                block size is 1
    linear system matrix = precond matrix:
    Mat Object:     1 MPI processes
      type: seqsbaij
      rows=2, cols=2
      total: nonzeros=3, allocated nonzeros=3
      total number of mallocs used during MatSetValues calls =0
          block size is 1
  linear system matrix = precond matrix:
  Mat Object:  C   4 MPI processes
    type: mpisbaij
    rows=8, cols=8
(3) 18:52:42 [mapping::PetRadialBasisFctMapping]:751 in map: ERROR: RBF linear system has not converged.
(1) 18:52:42 [mapping::PetRadialBasisFctMapping]:751 in map: ERROR: RBF linear system has not converged.
(2) 18:52:42 [mapping::PetRadialBasisFctMapping]:751 in map: ERROR: RBF linear system has not converged.
    total: nonzeros=36, allocated nonzeros=36
    total number of mallocs used during MatSetValues calls =0
        block size is 1
(0) 18:52:42 [mapping::PetRadialBasisFctMapping]:751 in map: ERROR: RBF linear system has not converged.
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19748,1],0]
  Exit code:    255
--------------------------------------------------------------------------

      Start 11: precice.math
11/20 Test #11: precice.math .....................   Passed    0.38 sec
      Start 12: precice.mesh
12/20 Test #12: precice.mesh .....................   Passed    0.41 sec
      Start 13: precice.partition
13/20 Test #13: precice.partition ................   Passed    3.92 sec
      Start 14: precice.interface
14/20 Test #14: precice.interface ................   Passed    0.39 sec
      Start 15: precice.serial
15/20 Test #15: precice.serial ...................   Passed   10.94 sec
      Start 16: precice.parallel
16/20 Test #16: precice.parallel .................***Timeout  20.02 sec
Running 10 test cases...
Running 10 test cases...
Running 10 test cases...
Running 10 test cases...
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(1) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(2) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
(0) 18:53:03 [acceleration::QRFactorization]:394 in orthogonalize: WARNING: Matrix Q is not sufficiently orthogonal. Failed to rorthogonalize new column after 4 iterations. New column will be discarded. The least-squares system is very bad conditioned and the quasi-Newton will most probably fail to converge.
[tester-VirtualBox:05511] PACK-PMIX-VALUE: UNSUPPORTED TYPE 0
[tester-VirtualBox:05511] PMIX ERROR: ERROR in file src/server/pmix_server.c at line 1956

      Start 17: precice.query
17/20 Test #17: precice.query ....................   Passed    0.40 sec
      Start 18: precice.testing
18/20 Test #18: precice.testing ..................   Passed    0.76 sec
      Start 19: precice.utils
19/20 Test #19: precice.utils ....................   Passed    0.50 sec
      Start 20: precice.xml
20/20 Test #20: precice.xml ......................   Passed    0.79 sec

75% tests passed, 5 tests failed out of 20

Label Time Summary:
canfail     =  40.04 sec*proc (2 tests)
mpiports    =  40.04 sec*proc (2 tests)
petsc       =   5.56 sec*proc (1 test)

Total Test time (real) = 120.98 sec

The following tests FAILED:
	  2 - precice.action (Timeout)
	  4 - precice.com.mpiports (Timeout)
	  8 - precice.m2n.mpiports (Timeout)
	 10 - precice.mapping.petrbf (Failed)
	 16 - precice.parallel (Timeout)
Errors while running CTest
Makefile:105: recipe for target 'test' failed
make: *** [test] Error 8
```
</p>
</details>

I am using the following state of preCICE:
```
commit 50b4ae865998457f6d96474e1fecda89ec082fcd (HEAD -> release-v2.0.0, origin/release-v2.0.0)
Author: Frédéric Simonis <simonisfrederic@gmail.com>
Date:   Mon Feb 3 13:15:06 2020 +0100

    Bump version to 2.0.0

commit 6630c77a76b51503a09cd4c2f8425d976aa46bb9 (origin/develop, origin/HEAD)
Author: Frédéric Simonis <simonisfrederic@gmail.com>
Date:   Wed Feb 5 12:45:01 2020 +0100

    Fix and reword the main doxygen page
```

No other version of preCICE was ever installed in this VM. No Python bindings. `ccmake` shows that I have enabled the PythonActions variable.

**Comment by uekerman** [comment]
The `parallel` integration test problem seems to be MPI ports problem again. So, not unexpected for Ubuntu 18.04, but it apparently only fails sometimes. This should get better in the future when we refactor the tests. I would vote for ignoring this at the moment. 

Concerning `action` unit tests: could it be some missing dependency? Does the behavior change when you install numpy?

**Comment by MakisH** [comment]
> Concerning `action` unit tests: could it be some missing dependency? Does the behavior change when you install numpy?

YES! Installing numpy makes `precice.action` succeed. @fsimonis can we make CMake to also check for numpy?

**Comment by fsimonis** [comment]
@MakisH we could force CMake to only look for the result of `numpy.get_include()`.

**Comment by BenjaminRueth** [comment]
> @MakisH we could force CMake to only look for the result of `numpy.get_include()`.

I'm using a similar approach in the [python bindings](https://github.com/precice/python-bindings/blob/ab6a66e7bd8b975e2cfc56940c3034eafd3217cc/setup.py#L68).

**Comment by fsimonis** [comment]
I added a `Finding Python and NumPY` section to the CMake wiki page.

**Comment by atotoun** [comment]
Amin Totounferoush is inviting you to a scheduled Zoom meeting.

Topic: [precice/precice] Release v2.0.0 (#657)
Time: Feb 7, 2020 10:00 AM Eastern Time (US and Canada)

Join Zoom Meeting
https://zoom.us/j/275850261?pwd=RlZ5MVBIdjJtYXloK2M3dkQyM1RKUT09

Meeting ID: 275 850 261
Password: 353dh0

One tap mobile
+16465588656,,275850261# US (New York)
+14086380968,,275850261# US (San Jose)

Dial by your location
+1 646 558 8656 US (New York)
+1 408 638 0968 US (San Jose)
Meeting ID: 275 850 261
Find your local number: https://zoom.us/u/actZPFt1kO

**Pull request merged**
