### PR TITLE
Mesh test incomplete test

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds a mesh test with points close to zero in order to debug #603 

@MakisH Can you reproduce the error with this test?

Command to run `./testprecice --run_test=MeshTests/VerticesCloseToAxis --log_level=all`

### CODE REVIEW

**Comment by MakisH** [comment]
I am not sure what I am doing wrong at the moment, but I cannot select tests. Executing any of the following returns `Test setup error: no test cases matching filter or all test cases were disabled`:

```
./testprecice --run_test=MeshTests/VerticesCloseToAxis --log_level=all
./testprecice -t "MeshTests/VerticesCloseToAxis" --log_level=all
./testprecice -t "*/*VerticesClose*" --log_level=all
```

The problem still occurs with the "problematic" Eigen version. Running all the tests with `make test` does not raise any failures.

**Comment by uekerman** [comment]
I guess it needs to be:
```
./testprecice --run_test="MeshTests/MeshTests/VerticesCloseToAxis"
```
Tests currently always have three layers (two test suites and the name of the test). It' a bit weird here though that both layers have the same name.

But
>Running all the tests with make test does not raise any failures.

already answers the question: the problem is apparently not reproducible with the test.

**Comment by MakisH** [comment]
> I guess it needs to be:
> 
> ```
> ./testprecice --run_test="MeshTests/MeshTests/VerticesCloseToAxis"
> ```
Thank you, this worked! I guess we need to heavily edit our [Tests](https://github.com/precice/precice/wiki/Tests) wiki page.

So, here is the output:
```
$ ./testprecice --run_test="MeshTests/MeshTests/VerticesCloseToAxis" --log_level=all
Running tests on less than four processors. Not all tests are executed.
Running 1 test case...
Entering test module "preCICE Tests"
/home/makish/github/precice_fsimonis/src/mesh/tests/DataConfigurationTest.cpp(7): Entering test suite "MeshTests"
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(19): Entering test suite "MeshTests"
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(447): Entering test case "VerticesCloseToAxis"
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(471): info: check mesh.vertices().size() == 6 has passed
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(479): info: check mesh.edges().size() == 6 has passed
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(483): info: check mesh.triangles().size() == 2 has passed
(0) 11:08:06 [mesh::Mesh]:206 in allocateDataValues: Data Data now has 6 values
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(486): info: check mesh.data().size() == 1 has passed
(0) 11:08:06 [mesh::Mesh]:299 in computeBoundingBox: BoundingBox, dim: 0, first: 1.3e-06, second: 1
(0) 11:08:06 [mesh::Mesh]:299 in computeBoundingBox: BoundingBox, dim: 1, first: -1, second: 1
(0) 11:08:06 [mesh::Mesh]:299 in computeBoundingBox: BoundingBox, dim: 2, first: -0.999999, second: 1.3e-06
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(447): Leaving test case "VerticesCloseToAxis"; testing time: 1941us
/home/makish/github/precice_fsimonis/src/mesh/tests/MeshTest.cpp(19): Leaving test suite "MeshTests"; testing time: 1970us
/home/makish/github/precice_fsimonis/src/mesh/tests/DataConfigurationTest.cpp(7): Leaving test suite "MeshTests"; testing time: 1997us
Leaving test module "preCICE Tests"; testing time: 2032us

*** No errors detected
(0) 11:08:06 [utils::Events]:58 in stop: Stopped event _GLOBAL
(0) 11:08:06 [utils::Parallel]:152 in finalizeMPI: preCICE finalizes MPI
```

**Comment by uekerman** [comment]
Should we still merge this test? Does not hurt to keep the test, I guess.

**Comment by MakisH** [comment]
We have not reproduced a case where the test fails, so I am not sure if it would be good to have a test that we don't know if it fails.

**Comment by uekerman** [comment]
No, the test should / does not fail if Eigen behaves as expected.

**Comment by MakisH** [comment]
> No, the test should / does not fail if Eigen behaves as expected.

You mean it could still fail in another situation? This would then be a test of Eigen, not of preCICE (which is not necessarily bad). Let's keep the test, but it then let's not relate it with this issue.

**Comment by fsimonis** [comment]
I reworked the test to check `computeState()` for an incompletely connected mesh.

**Pull request merged**
