### PR TITLE
Add trailing whitespace and newline pre-commit hooks

### PR DESCRIPTION
**Pull request by DavidSCN**
## Main changes of this PR
...which prevents git whitespace errors and enforces a common ending of files in the database.

## Author's checklist

* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I ran `make format` to ensure everything is formatted correctly.
* [ ] I sticked to C++14 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [x] Does the changelog entry make sense? Is it formatted correctly?
* [x] Do you understand the code changes?

### CODE REVIEW

**Review by MakisH — APPROVED** [review]
Nice! I did not try it, but it seems like the added pre-commit removes trailing spaces from the end of every line and every file. I hope there was no reason to keep an empty line at the end of some file.

**Comment by fsimonis** [comment]
Double tailing whitespaces are linebreaks in Markdown.
Is there a setting to preserve this special case?

**Comment by DavidSCN** [comment]
> Double tailing whitespaces are linebreaks in Markdown.
Is there a setting to preserve this special case?

Apparently yes, added it, although I'm not sure whether using this line break is a good idea with git.

**Review by fsimonis — APPROVED** [review]
Nice, let's get this merged.

@DavidSCN The double whitespace is important for the changelog.

**Pull request merged**
