### PR TITLE
Fix intel compiler issues

### PR DESCRIPTION
**Pull request by mennodeij**
Two small things that gave problems when compiling with Intel compilers:

1. fix the usage of the BOOST_TEST_INFO macro when directly applied to a variable of type `map<int,vector<int>>`
2. usage of `REAL(8)` instead of `REAL` when used with a `double` variable in C++

### CODE REVIEW

**Comment by fsimonis** [comment]
Thanks for the hints!

> fix the usage of the BOOST_TEST_INFO macro when directly applied to a variable of type map<int,vector<int>>

We need a solution to the problem instead of a quick fix. I will investigate this a bit further. Can you please provide the full error message emitted by the intel compiler?

> usage of REAL(8) instead of REAL when used with a double variable in C++

Good point! For the sake of consistency and readability, we should use `DOUBLE PRECISION` instead of `REAL(8)` though.
@MakisH could this be an issue in further Fortran codes?

**Comment by mennodeij** [comment]
The full error message is found in #856

**Comment by fsimonis** [comment]
You are quick! Just altered my answer. Thanks again!

**Comment by MakisH** [comment]
> Good point! For the sake of consistency and readability, we should use `DOUBLE PRECISION` instead of `REAL(8)` though.
> @MakisH could this be an issue in further Fortran codes?

`DOUBLE PRECISION` would indeed be clearer, more consistent, and maybe safer than specifying the number of bytes. Fortran also provides [`kind`s](http://fortranwiki.org/fortran/show/Real+precision), but this is another topic.

In the Fortran module [we also currently use `real(8)`](https://github.com/precice/fortran-module/blob/9826f277e3302cc1aef50741530538bd9d8d23c7/examples/solverdummy/solverdummy.f03#L11).

**Comment by fsimonis** [comment]
Let's split this PR into 2 parts.

I committed your Fortran fix in 10a958233cc372f41c0df8c5025183b552edb081 and annotated you as the author to keep your contribution in the system.
The intel issue is more delicate and I am currently attempting to figure out how to solve the issue.

Thank you for your contribution!

**Pull request closed without merging**
