### PR TITLE
Add systemtests indicator

### LINKED ISSUE #294: Add a system tests status indicator in README
We have this nice "build status" in the preCICE README, which shows if the building and unit/integration tests succeeded/failed.

Since we now have nightly runs of our system tests, let's add another button for the system tests. For example: "tests:passing". Or "system tests:passing", if space allows.

If space is too short, we can remove the licence indicator, which is static and not so useful.

### PR DESCRIPTION
**Pull request by shkodm**
Closes #294

### CODE REVIEW

**Comment by MakisH** [comment]
Let's merge this when we fix the currently failining python bindings tests (#296).

**Comment by fsimonis** [comment]
@shkodm Do you know why the status shield shows `failing` even though it isn't?

**Comment by MakisH** [comment]
@fsimonis I think we need to specify the branch as well, otherwise it picks the latest build, which currently is a failing PR. But it doesn't make sense to specify the branch in the README... :-/ Check the image source on the respective button on the Travis page.

**Comment by shkodm** [comment]
Right, it picks up latest build ( and in that case it was failing PR ).  I haven't though of it. We should point to a master branch, like: 
```
 https://img.shields.io/travis/precice/systemtests/master.svg?label=system%20tests&style=flat

**Pull request merged**
