### PR TITLE
Fortran bindings: Rename inconsistently named functions

### PR DESCRIPTION
**Pull request by MakisH**
Related to #520.

### CODE REVIEW

**Comment by MakisH** [comment]
I currently get a strange error when running the Fortran solver dummy, also in develop, and always in the second participant:

```
DUMMY: Starting Fortran solver dummy...
preCICE: This is preCICE version 2.0.2
preCICE: Revision info: v2.0.2-189-g493f85a
preCICE: Configuring preCICE with configuration "../precice-config.xml"
preCICE: I am participant "SolverTwo"
preCICE: Setting up master communication to coupling partner/s
preCICE:ERROR:  Accepting a socket connection at  failed with the system error: Unknown error -1
*** Error in `./solverdummy': free(): invalid pointer: 0x00007f1decf25ce8 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777f5)[0x7f1decbd87f5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8038a)[0x7f1decbe138a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f1decbe558c]
/home/makish/github/precice/build/libprecice.so.2(_ZN9__gnu_cxx13new_allocatorISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS6_3_V212steady_clockENS6_8durationIlSt5ratioILl1ELl1000000000EEEEEEEE10deallocateEPSF_m+0x20)[0x7f1dee3c0ca8]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt16allocator_traitsISaISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEEEE10deallocateERSF_PSE_m+0x2b)[0x7f1dee3c057e]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt12_Vector_baseISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEESaISE_EE13_M_deallocateEPSE_m+0x32)[0x7f1dee3bf978]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt6vectorISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEESaISE_EE15_M_range_insertIN9__gnu_cxx17__normal_iteratorIPKSE_SG_EEEEvNSJ_IPSE_SG_EET_SP_St20forward_iterator_tag+0x376)[0x7f1dee3d37b8]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt6vectorISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEESaISE_EE18_M_insert_dispatchIN9__gnu_cxx17__normal_iteratorIPKSE_SG_EEEEvNSJ_IPSE_SG_EET_SP_St12__false_type+0x45)[0x7f1dee3cdbb3]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt6vectorISt4pairIN7precice5utils5Event5StateENSt6chrono10time_pointINS5_3_V212steady_clockENS5_8durationIlSt5ratioILl1ELl1000000000EEEEEEESaISE_EE6insertIN9__gnu_cxx17__normal_iteratorIPKSE_SG_EEvEENSJ_IPSE_SG_EESM_T_SP_+0x8e)[0x7f1dee3c93e2]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice5utils9EventData3putERKNS0_5EventE+0x1fe)[0x7f1dee3c1b44]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice5utils8RankData3putERKNS0_5EventE+0x9a)[0x7f1dee3c1e22]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice5utils13EventRegistry3putERKNS0_5EventE+0x27)[0x7f1dee3c25c1]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice5utils5Event4stopEb+0x116)[0x7f1dee3be6b4]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice4impl19SolverInterfaceImpl8finalizeEv+0x1007)[0x7f1dee37ad79]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice4impl19SolverInterfaceImplD1Ev+0x96)[0x7f1dee373dca]
/home/makish/github/precice/build/libprecice.so.2(_ZNKSt14default_deleteIN7precice4impl19SolverInterfaceImplEEclEPS2_+0x22)[0x7f1dee3559a2]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt10unique_ptrIN7precice4impl19SolverInterfaceImplESt14default_deleteIS2_EED1Ev+0x47)[0x7f1dee3558dd]
/home/makish/github/precice/build/libprecice.so.2(_ZN7precice15SolverInterfaceD1Ev+0x18)[0x7f1dee354cf4]
/home/makish/github/precice/build/libprecice.so.2(_ZNKSt14default_deleteIN7precice15SolverInterfaceEEclEPS1_+0x22)[0x7f1dee451886]
/home/makish/github/precice/build/libprecice.so.2(_ZNSt10unique_ptrIN7precice15SolverInterfaceESt14default_deleteIS1_EED1Ev+0x47)[0x7f1dee451725]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x9a)[0x7f1decb9b37a]
/home/makish/github/precice/build/libprecice.so.2(+0xc82cf3)[0x7f1dededecf3]
```

Therefore, I cannot test this at the moment.

**Comment by uekerman** [comment]
> I currently get a strange error when running the Fortran solver dummy, also in develop, and always in the second participant:

Looks like a system error to me. Try restarting your computer :see_no_evil: 
Fortran solverdummy just worked for me #540

**Comment by uekerman** [comment]
You also have similar problems for:

https://github.com/precice/precice/blob/4aa6a302def46bb2fbc85bcd7263d4c08fe16183/extras/bindings/fortran/src/SolverInterfaceFortran.cpp#L97

https://github.com/precice/precice/blob/4aa6a302def46bb2fbc85bcd7263d4c08fe16183/extras/bindings/fortran/src/SolverInterfaceFortran.cpp#L109

**Comment by MakisH** [comment]
@IshaanDesai this is ready for review. Does it work for you? Did we miss anything else?

**Comment by uekerman** [comment]
Can we already open an issue to remind us to remove the deprecated functions with v3.0?

**Pull request merged**
