### PR TITLE
Add DaRUS badge to README

### PR DESCRIPTION
**Pull request by uekerman**
Do we want to put such a badge here? Feel free to modify.
Will probably only work once published on DaRUS, hence the draft.

### CODE REVIEW

**Review by MakisH — COMMENTED** [review]
We should definitely add a badge, yes!

However, shouldn't we better put it under "project status"?

Another question: how do we want to treat this DOI once we have our new reference paper published? What do we want people to cite? How should we guide them between the two options?

We could also make our own badge "preCICE distribution" that shows the version instead of the DOI, but it still links there.

**Comment by uekerman** [comment]
> However, shouldn't we better put it under "project status"?

Yes, right.

> Another question: how do we want to treat this DOI once we have our new reference paper published? What do we want people to cite? How should we guide them between the two options?

That's an important question, which we should discuss in detail. I'll add it to the next telco.

**Comment by uekerman** [comment]
I updated the badge to distribution v2202 and moved it to the project status section.

**Review by MakisH — APPROVED** [review]
That's already nice! Just to clarify: if I am an external and see a repository mentioning a DOI (as here), I will directly assume this is the citation. This may be a bit confusing for now, since we also have the "what to cite" at the bottom, but I guess we will tidy this up once we also have the v2 paper online.

By the way, do we want to push/wait to also have the v2 paper in v2.4?

**Comment by uekerman** [comment]
> By the way, do we want to push/wait to also have the v2 paper in v2.4?

You mean in the README?

**Comment by MakisH** [comment]
> > By the way, do we want to push/wait to also have the v2 paper in v2.4?
> 
> You mean in the README?

yes, since we have the 2016 paper at the bottom of the README.

**Comment by uekerman** [comment]
> By the way, do we want to push/wait to also have the v2 paper in v2.4?

I guess this is a unnecessary dependency. In the end, it's not so important what is in the README of the release, but what we have on develop (meaning rendered on the default branch on GitHub).
Let's update this, once we do all the "new paper updates".

Merging here.

**Pull request merged**
