### PR TITLE
Fix preCICE on Boost 1.69

### PR DESCRIPTION
**Pull request by Summerdave**
Boost.Test 1.69 is broken on preCICE. There are two issues:

1.  `collector` became `collector_t`
Fixed by this PR with a simple `#if` preprocessor directive.
2. At runtime `testprecice` fails at:
https://github.com/precice/precice/blob/d601da73c78bf684fa986bb4e2d81861fc96b982/src/testing/main.cpp#L47
This is caused by a bug in Boost.Test, which is discussed [there](https://github.com/boostorg/test/issues/199). It only affects preCICE in boost version 1.69, as the author already fixed it. This does, however, pose the question of how we should handle it. Suggestions are welcome :).

### CODE REVIEW

**Comment by fsimonis** [comment]
@Summerdave It doesn't _feel right_, but we could simply `#if` the problem out of existence for boost 1.69 by printing a __bold__ warning and setting the loglevel to debug.

**Comment by floli** [comment]
The first part of the fix is already included in https://github.com/precice/precice/tree/fix_for_boost_1.69
For the second part, the runtime error, I don't see no good solution at this time.

BTW: What is the CMakeLists.txt change about?

**Comment by fsimonis** [comment]
@floli We are linking against a list of libraries, so the include directories were indeed missing.

**Comment by floli** [comment]
Shouldn't it be rather `PRIVATE`, since boost is not part of our public interface?

I will not merge this PR, instead take over the relevant part to the before-mentioned branch.

@fsimonis Do you take over the missing boost include into your cmake overhaul branch?

**Comment by fsimonis** [comment]
@floli Yes, it should be private, but It wont matter as our dependencies should all be private. I fixed this and the missing include in #240.

**Pull request closed without merging**
