### PR TITLE
Release 3.0.1

### PR DESCRIPTION
**Pull request by fsimonis**
This is the bugfix release v3.0.1, which fixes some time-handling issues with long-running simulations.

Given that this is a direct follow-up to the release 3.0.0, this release is a straight merge from develop instead of main.

## How to work with this template

* [x] assign a release manager, who takes care of the process
* [ ] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Pre-PR steps

* [x] Make sure you have the latest `main` branch locally.
* [x] ~~Create branch `hotfix-vX.Y.Z` from `main`. If needed, `git rebase main`.~~ in this case directly from develop
* [x] Commit fixes to the hotfix branch
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [ ] ~~Update the list of operating systems for the package generation in `.github/workflows/release.yml`~~ done on develop
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version
* [x] Look over the updated `CHANGELOG.md` of the hotfix branch (all)
   * Check for merged lines
   * Add things, if necessary
   * Fix wording and tense
   * Sort the entries lexicographically
   * Extract summary
* [x] Verify the version changes in:
   * [x] `CHANGELOG`
   * [x] `CMakeLists.txt`
   * [x] `tools/releasing/packaging/debian/changelog`
* [x] Commit the version bump
* [x] Push the hotfix branch to the precice repository
* Prepare independent hotfixes
   * [ ] [Python bindings](https://github.com/precice/python-bindings/blob/develop/docs/hotfixGuide.md)
   * [ ] (if necessary!) [MATLAB bindings](https://github.com/precice/matlab-bindings/blob/develop/docs/hotfixGuide.md)
   * [ ] (if necessary!) [JULIA bindings](https://github.com/precice/PreCICE.jl)

## Step by step guide

* [x] Open PR from `hotfix-vX.Y.Z` to `main` (use [this template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md))
* [ ] Do regression tests using the hotfix branch (specific revision) _list below :arrow_down:_ (all)
* [ ] Fix potential problems on the hotfix branch (all)
* [ ] Reorder the commits for the version bump to be the latest. `git rebase -i main`
* [ ] Draft message to mailing list
* [ ] Write a draft "blog post" on [Discourse](https://precice.discourse.group/)
* [ ] Approve the PR with at least two reviews (all)
* [ ] Merge PR to `main` ( use `git merge --no-ff hotfix-vX.Y.Z` )
* [ ] Tag hotfix on `main` `vX.Y.Z` and verify by running `git describe --tags`
* [ ] Merge `main` back to `develop` and verify by running `git describe --tags`
* [ ] Triple check that you haven't messed anything up. (You can always discard local changes)
* [ ] Push `main` and push the `vX.Y.Z` tag
* [ ] Push `develop`
* [ ] Wait for the release pipeline
  * [ ] [To create a new draft hotfix on GitHub](https://github.com/precice/precice/releases)
  * [ ] To automatically generate packages for the latest Debian and the two latest Ubuntu LTS versions.
* [ ] Write hotfix text
* [ ] Publish the GitHub hotfix

## Regression Tests

Use the following branches:
* precice `hotfix-vX.Y.Z`
* pyprecice `python-bindings-vX.Y.Z.1`
* matlab-bindings `matlab-bindings-vX.Y.Z.1`
* rest `main`(`master`)

Run all these tests manually on your system. If you succeed, please write a comment with the revisions of the components that you used below. Example: https://github.com/precice/precice/pull/507#issuecomment-530432289 and update the table.

| State | Success | Failure | Skipped |
| --- | --- | --- | --- |
| Write | `:o:` | `:x:` | `:fast_forward:` |
| Read | :o: | :x: | :fast_forward: |

| State | Tester | Test |
| --- | --- | --- |
| | | [elastic-tube-1d](https://github.com/precice/tutorials/tree/master/elastic-tube-1d) fluid-cpp - solid-python |
| | | Solverdummy [Fortran module](https://github.com/precice/fortran-module/tree/develop/examples/solverdummy) |
| | | Solverdummy [Python](https://github.com/precice/python-bindings/tree/develop/solverdummy) |

## Post-release

* [ ] Update version specific documentation
* [ ] Flag [Arch Linux AUR package](https://aur.archlinux.org/packages/precice) and dependants as out-of-date.
* [ ] Update Spack recipe
* [ ] Update `pyprecice` Spack
* [ ] Update Website:
    * [ ] Bump version in [`_config.yml`](https://github.com/precice/precice.github.io/blob/master/_config.yml)
    * [ ] Update the [XML reference](https://github.com/precice/precice.github.io/blob/master/_includes/xmlreference.md) using `binprecice md`
    * [ ] Look over the [Roadmap](https://www.precice.org/fundamentals-roadmap.html) and update entries.

### Release new version for bindings (to ensure compatibility with newest preCICE version)

- [ ] [python bindings](https://github.com/precice/python-bindings/blob/develop/docs/hotfixGuide.md)

### Marketing

* [ ] Write on [Matrix](https://matrix.to/#/#precice_lobby:gitter.im?web-instance[element.io]=app.gitter.im)
* We announce this together with the upcoming distribution release.

### Misc

* [ ] Update the [PR template](https://github.com/precice/precice/blob/develop/tools/releasing/PULL_REQUEST_TEMPLATE/hotfix_pull_request_template.md)

To open a new PR with this template, use this [PR template query](https://github.com/precice/precice/compare/new?template=hotfix_pull_request_template.md)

### CODE REVIEW

**Review by davidscn — CHANGES_REQUESTED** [review]
>  this release is a straight merge from develop instead of main.

I would vote against this. The changes declared here as bugfix are definitely more than a bugfix. We change the behavior in various places, e.g., using `std::filesystem` instead of boost or in the config parser. This makes it very intransparent for the user what has actually been fixed. It could also be that we end up releasing yet another bugfix of this preCICE version. What do we include then? Why not cherry-picking just the two issues we discovered so far?

**Comment by fsimonis** [comment]
> The changes declared here as bugfix are definitely more than a bugfix.

We had this discussion locally a few times too. While these changes look like a lot, they aren't very impactfull. Fundamentlally, we drop boost filesystem as a dependency as `std::filesystem` is shipped with `glibc++`. So, this is very borderline in terms of minor vs patch release

Given the extra work involved cherry picking for a bugfix, I would suggest to either keep it as a patch `3.0.1` or turn it into a minor release `3.1.0`.

**Comment by MakisH** [comment]
> I have not participated in such a discussion.

I raised the same arguments in-person last week. The counter-argument was that it was complicated to extract the bugfix from the current state, as changes already merged in develop have changed the respective code (I have no clue).

**Comment by MakisH** [comment]
Then let's do a v3.1.0.

**Comment by uekerman** [comment]
> Then let's do a v3.1.0.

Agree as well.

@fsimonis I guess you close this PR and open a new one?

**Comment by fsimonis** [comment]
> I guess you close this PR and open a new one?

Yep. That makes things a bit cleaner.

**Comment by fsimonis** [comment]
https://github.com/precice/precice/pull/1983#issuecomment-2015509638

There is a (positive) explanation for this, see #1984 for more information.

Closing now and preparing the v3.1.0 update.

**Pull request closed without merging**
