### PR TITLE
Remove resetWrittenData

### PR DESCRIPTION
**Pull request by BenjaminRodenberg**
## Main changes of this PR

Removes the unneeded/untested function `SolverInterfaceImpl::resetWrittenData`.

## Motivation and additional information

In #1029 this function has been identified as not required for (tested) functionality. It, additionally, makes the implementation more complicated. This PR removes the function as suggested in https://github.com/precice/precice/issues/1156.

## Author's checklist

* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [x] I ran `make format` to ensure everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [x] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by uekerman** [comment]
I guess if we do this change we could simply remove `hasReadMapping()` and `hasWriteMapping()`. These functions seem to have no real purpose anymore.

**Comment by BenjaminRodenberg** [comment]
> I guess if we do this change we could simply remove `hasReadMapping()` and `hasWriteMapping()`. These functions seem to have no real purpose anymore.

These functions are protected now. I think they are still helpful for better readability and testing.

**Comment by uekerman** [comment]
Are we sure we want this? See discussion in #1156 
Let's try to first conclude there.

**Comment by BenjaminRodenberg** [comment]
I added a `breaking change` label now, because this seems to be more complicated that I expected. My suggestion: I will try to make https://github.com/precice/precice/pull/1029 independent from this PR, then merging this PR is not critical anymore and we can take our time and first conclude on #1156. We can still just keep this PR open, because the implementation is basically done. We just don't know whether we want to merge it.

**Comment by BenjaminRodenberg** [comment]
#1029 is now independent from this one. So we can also wait with this PR from my perspective.

**Comment by uekerman** [comment]
Let's conclude in #1156 first.

**Comment by BenjaminRodenberg** [comment]
> Let's conclude in #1156 first.

Agreed. Handing this PR over to you then.

**Comment by fsimonis** [comment]
We concluded to keep this functionality https://github.com/precice/precice/issues/1156#issuecomment-1517994385

**Pull request closed without merging**
