### PR TITLE
Bump version on develop to 3.0.0

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR bumps the version on develop to 3.0.0.

It also adds a manual conflict with libprecice2 and declares it to provide the `preCICE` virtual package. This should cover future major versions.

## Motivation and additional information

This should simplify porting dependants of the preCICE core.

Generated Debian packages and pkg-config should work too.
Note that this will change the major version, which is part of the Debian package name. So this one directly conflicts with the old one.

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [x] I sticked to C++17 features.
* [x] I sticked to CMake version 3.16.3.
* [x] I squashed / am about to squash all commits that should be seen as one.

### CODE REVIEW

**Comment by davidscn** [comment]
> Note that this will change the major version, which is part of the Debian package name. So this one directly conflicts with the old one.

Yes, but the symlink should point to the latest installation such that linking works as expected. Also, one could (and probably should) always run `make uninstall` in the previous build dir to prevent such conflicts.

I'm in favor of such a change. I'm not sure how correct our version string will be rendered, though `This is preCICE version 3.0.0 - <commits after v2.5.0>. Some pre-release marking could still be useful to not get confused when jumping back and forth between dev and release version in the future.

**Comment by davidscn** [comment]
> I have an idea. Maybe we can declare preCICE as a virtual package and declare a conflict with the virtual preCICE package for upcoming major releases as well as explicitly declaring a conflict for libprecice2.

I think we are not the first package to have a new major release. How do other packages handle this? To some extend this is a problem of the user. I would just go with the default debian way, but if this sounds convincing to you, go ahead.

**Comment by fsimonis** [comment]
Tried this in a docker container and it works!
It even works both ways, so installing the libprecice2 will replace the libprecice3 package. 

```console
# apt install ./libprecice2_2.5.0_focal.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libprecice2' instead of './libprecice2_2.5.0_focal.deb'
The following NEW packages will be installed:
  libprecice2
0 upgraded, 1 newly installed, 0 to remove and 12 not upgraded.

# precice-tools version
2.5.0;no-info [git failed to run];PRECICE_MPICommunication=Y;PRECICE_PETScMapping=Y;PRECICE_PythonActions=Y;PRECICE_ENABLE_C=Y;PRECICE_ENABLE_FORTRAN=Y;CXX=GNU;CXXFLAGS= -O3 -DNDEBUG;LDFAGS=

# apt install ./libprecice3_3.0.0_focal.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libprecice3' instead of './libprecice3_3.0.0_focal.deb'
The following packages will be REMOVED:
  libprecice2
The following NEW packages will be installed:
  libprecice3
0 upgraded, 1 newly installed, 1 to remove and 12 not upgraded.
Need to get 0 B/3391 kB of archives.
After this operation, 26.5 MB of additional disk space will be used.
Do you want to continue? [Y/n]

# precice-tools version
3.0.0;no-info [not a repository];PRECICE_MPICommunication=Y;PRECICE_PETScMapping=Y;PRECICE_PythonActions=Y;PRECICE_ENABLE_C=Y;PRECICE_ENABLE_FORTRAN=Y;CXX=GNU;CXXFLAGS= -g;LDFLAGS=

# apt install ./libprecice2_2.5.0_focal.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libprecice2' instead of './libprecice2_2.5.0_focal.deb'
The following packages will be REMOVED:
  libprecice3
The following NEW packages will be installed:
  libprecice2
0 upgraded, 1 newly installed, 1 to remove and 12 not upgraded.
Need to get 0 B/1662 kB of archives.
After this operation, 26.5 MB disk space will be freed.
Do you want to continue? [Y/n]
```

**Comment by fsimonis** [comment]
Squashed some fixes and rebased. The arch CI still fails until openmpi 4.1.6 is released.

**Pull request merged**
