### PR TITLE
WIP: moved geo id reset, workaround for #378

### PR DESCRIPTION
**Pull request by uekerman**
see #378

### CODE REVIEW

**Comment by uekerman** [comment]
@Dominanz

**Comment by Dominanz** [comment]
Thanks a lot!

**Comment by uekerman** [comment]
@Dominanz Does it solve your problem?

**Comment by Dominanz** [comment]
Yes, indeed!

**Comment by fsimonis** [comment]
I am closing this PR as we need a proper solution for this issue.
Refer to #655 for future reference.

**Pull request closed without merging**
