### PR TITLE
Change default mpi com in m2n to MPISinglePortsCom

### PR DESCRIPTION
**Pull request by uekerman**
`MPISinglePortsCom` is the more efficient variant developed by @floli. `MPIPortsCom` is the old, now kind of deprecated, variant. This PR changes the default setting. `"mpi"` now points to the new implementation and the old variant is accessible via `"mpi-multiple-ports"`. 
In my opinion it is still too early to completely remove the old implementation.

### CODE REVIEW

**Comment by uekerman** [comment]
All test involving `MPISinglePortsCom` currently fail, the new unit tests and the integration tests. I am not sure of the reason currently and would therefore move the PR to the next release.

**Comment by fsimonis** [comment]
I rebased this branch on develop ( I had to drop 57861e2 ) and all tests pass.

We now need to restore the naming of test configuration files and maybe also add some more to test both `mpi` and  `mpi-multiple-ports`.

**Comment by fsimonis** [comment]
I pushed the rebased version of this PR.

**Comment by fsimonis** [comment]
Merge this after the release 2.1.0.
There is still more testing to be done.

**Comment by fsimonis** [comment]
Let's rebase this on develop an check if it still works.

**Comment by BenjaminRodenberg** [comment]
This PR is now rebased on top of the current state of develop (1a5f5d9cfb39769534ebbdfe0d4f645feb25f591).

**Comment by fsimonis** [comment]
We should really keep the `mpi-singleports` tag to ensure backwards compatibility. This should not be too difficult.

**Comment by BenjaminRodenberg** [comment]
### Todos

- [ ] implement `mpi-singleports`
- [ ] run a parallel case to make sure this PR does not break anything (i.e. parallel fenics-fenics)
- [ ] add MPICH to github actions and run tests #713

**Comment by BenjaminRodenberg** [comment]
Currently I do not really have time to work on this PR. If somebody else would like to work on it, it's basically free.

**Comment by fsimonis** [comment]
I just rebased this on develop. Let's see how the tests do.

**Comment by fsimonis** [comment]
The mpiports tests still fail with OpenMPI 4.1.1.

So we could either leave it as it is or change `mpi` to use multiple ports for OpenMPI and single-ports for everything else.

**Comment by uekerman** [comment]
> The mpiports tests still fail with OpenMPI 4.1.1.

You mean they fail for the single-port implementation, but not for the multiple-ports implementation?
That is works with the old multiple-ports implementation is new to me.

We already give build-time and run-time warnings if OpenMPI is used, right?

**Comment by fsimonis** [comment]
> You mean they fail for the single-port implementation, but not for the multiple-ports implementation?
That is works with the old multiple-ports implementation is new to me.

Just checked again. Both implementations fail for OpenMPI.

> We already give build-time and run-time warnings if OpenMPI is used, right?

There are warnings in place #797

**Comment by uekerman** [comment]
> Just checked again. Both implementations fail for OpenMPI.

But that's not an argument to *not* merge this PR, right?

**Comment by fsimonis** [comment]
> But that's not an argument to not merge this PR, right?

True.

The last thing that is missing is the backwards-compatibility for the `mpi-singleports' option.

**Comment by fsimonis** [comment]
The configuration part works. Merging

**Pull request merged**
