### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by MakisH**
## Step by step guide
* [x] Merge master to develop (No commits after the release on master) @MakisH 
* [x] Create branch `release-N` from develop. If needed, `git rebase develop`. @MakisH 
* [x] Open PR from `release-N` to `master` @MakisH 
* [x] Look over CHANGELOG and add things if necessary and extract summary (all) @fsimonis 
* [x] Do regression tests using the release branch (specific revision) _list below :arrow_down:_ (all)
* [x] Bump version in CMakeLists.txt, SConstruct, and CHANGELOG (and Python bindings). @MakisH 
* [x] Draft message to mailing list @uekerman @MakisH 
* [x] Update documentation (all) @MakisH 
* [x] Fix potential problems in develop (all)
* [x] Approve the PR with two reviews
* [ ] Merge PR to master @MakisH 
* [ ] Tag release (on GitHub) and merge back to develop @MakisH 

## Regression Tests
* [x] SU2/CalculiX @MakisH 
* [x] OpenFOAM / OpenFOAM @MakisH 
* [x] OpenFOAM / OpenFOAM - NP mapping in OpenFOAM @MakisH
* [x] OpenFOAM / OpenFOAM fluid coupling module @MakisH 
* [x] OpenFOAM / CalculiX FSI (flap perp) @MakisH
* [x] OpenFOAM / CalculiX FSI - NP mapping in CalculiX (3DTube) @KyleDavisSA 
* [ ] OpenFOAM / CalculiX / OpenFOAM CHT (heat exchanger) @MakisH
* [ ] OpenFOAM / deal.II @MakisH 
* [x] [OpenFOAM / FEniCS](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-FEniCS) @BenjaminRueth 
* [x] [OpenFOAM / Nutils](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils) @BenjaminRueth 
* [x] [FEniCS / FEniCS](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) @BenjaminRueth 
* [x] ExaFSA: Ateles / FASTEST @atotoun 
* [x] Alya @uekerman 
* [x] 1D-ElasticTube (C++) @BenjaminRueth 
* [x] 1D-ElasticTube (Python) @BenjaminRueth @KyleDavisSA 
* [x] SuperMUC @fsimonis 
* [x] C++ Dummy @fsimonis 
* [x] C Dummy @fsimonis 
* [x] Fortran Dummy @fsimonis 
* [x] Fortran 2003 Dummy @fsimonis 
* [x] Python Dummy @fsimonis 

## Post-release
* [ ] Generate packages @shkodm @fsimonis 
   * [ ] Ubuntu 18.04
   * [ ] Ubuntu 19.04
   * [ ] Arch Linux AUR Package
* [ ] Update Spack recipe @fsimonis 
* [ ] Send email and do marketing @uekerman 
   * [ ] Mention [xSDK](https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/precice-policy-compatibility.md)
* [ ] Tweet @MakisH 
* [ ] Format the code base @shkodm @fsimonis 
* [x] Create a [PR templates](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) with this list. See https://github.com/precice/precice/pull/509

### CODE REVIEW

**Comment by MakisH** [comment]
We are testing the revision v1.5.2-153-gb584be8.

**Comment by fsimonis** [comment]
Tested Solverdummies: `C / C++ / Fortran / F2003 / python / python_future`

**Comment by atotoun** [comment]
Compiled Successfully on superMUC .

**Comment by MakisH** [comment]
Using preCICE v1.5.2-153-gb584be8:
* **OpenFOAM-OpenFOAM** `adapter/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam` works in serial (OpenFOAM adapter commit 6dc2f7a3, OpenFOAM v1906). The temperature surface plot looks reasonable and a temperature plot on a line crossing the interface looks smooth. The (now updated) **`Allclean` script** works as expected. This tutorial uses **NN mapping**.
* OpenFOAM-OpenFOAM `adapter/tutorials/CHT/flow-over-plate/buoyantPimpleFoam-laplacianFoam_nearest-projection` works in **serial and parallel** (OpenFOAM adapter commit 6dc2f7a3, OpenFOAM v1906). The temperature surface plot looks reasonable and a temperature plot on a line crossing the interface looks smooth. The (now updated) `Allclean` script works as expected. This tutorial uses **NP mapping**. There are no missing triangles.
* OpenFOAM-OpenFOAM fluid-fluid tutorial `adapter/tutorials/FF/pipe-pipe/pimpleFoam-pimpleFoam` works (OpenFOAM adapter commit 739323c3, OpenFOAM v1906). The pressure and velocity surface plots look reasonable. The (now updated) `Allclean` script works as expected.

**Comment by atotoun** [comment]
Gaussian pulse with a cubic domain test case (inner/outer both Ateles) works for nearest neighbor and nearest projection mapping.

**Comment by BenjaminRueth** [comment]
FEniCS / FEniCS is working:

**Comment by KyleDavisSA** [comment]
CalculiX Nearest Projection mapping works or the 3D Tube test case

**Comment by BenjaminRueth** [comment]
FEniCS / OpenFOAM is working. Used the following revisions:

* https://github.com/precice/tutorials/commit/a474a3adc092a6779f57816db5d4e1fe5c86b19d
* https://github.com/precice/fenics-adapter/commit/721dac5a282bf833af436356355a131da84f8663

**Comment by BenjaminRueth** [comment]
OpenFOAM (using OF6) / Nutils is working. Used the following revisions:

* https://github.com/evalf/nutils/commit/e3e82c8c30b79238641bc01ccec84c451041a160
* https://github.com/precice/openfoam-adapter/commit/f6133a8e5e131828c8c2f4155897017db923f8fc

**Comment by MakisH** [comment]
Using preCICE v1.5.2-153-gb584be8 (built in `Debug`, installed on a local path):

* OpenFOAM - **CalculiX** `tutorials/FSI/flap_perp/OpenFOAM-CalculiX` works in **serial and parallel** (OpenFOAM adapter commit 6dc2f7a3, OpenFOAM v1906, CalculiX 2.15, CalculiX adapter commit 59e06f11). The fluid surface plots look reasonable, the flap is oscillating as expected. This tutorial uses **PetRBF mapping**. The `Allclean` script works. 

* OpenFOAM - CalculiX `tutorials/FSI/cylinderFlap/OpenFOAM-CalculiX` runs for a while in serial without any errors. Skipping this as it would take a few hours and is very similar from feature perspective to the flap_perp. `Allclean` works fine.

* **OpenFOAM - CalculiX `tutorials/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX` fails for me with the following message:**
```
Initializing coupling data
Adapter writing coupling data...
(0) 17:22:58 [impl::SolverInterfaceImpl]:1063 in writeBlockScalarData: ERROR: There is no Data with ID 20
```
Here is the rest of the config: 
[Solid.log](https://github.com/precice/precice/files/3601550/Solid.log)


All my checks are with Ubuntu 16.04, OpenMPI 1.10.2, and PETSc 3.9.1 built from source.

**Comment by MakisH** [comment]
* **SU2** - CalculiX `tutorials/FSI/flap_perp/SU2-CalculiX` works fine in serial and parallel. The watchpoint plot looks ok (but the names of the watchpoints have changed, we need to update the script in the tutorial).

**Comment by MakisH** [comment]
The heat exchanger test failure that I get should be only in the adapter. Interestingly, it works for @KyleDavisSA. We decide to proceed with the release and make a bugfix release, if needed. It is important, however, as it is the only tutorial that covers 3 participants.

I skip the OpenFOAM - deal.II for now, as all the relevant features have been covered.

**Comment by MakisH** [comment]
The heat exchanger also works on Travis and on @uekerman 's system, so merging.

**Pull request merged**
