### PR TITLE
Adds storeIteration for initial write data

### PR DESCRIPTION
**Pull request by KyleDavisSA**
## Main changes of this PR

stores the `previousIteration` after calling `writeInitialData`. 

## Motivation and additional information

This PR closes https://github.com/precice/precice/issues/1034 and https://github.com/precice/precice/issues/1032

## Author's checklist

* [x] I added a changelog file with this PR number in `docs/changelog/` if there are noteworthy changes. -> Fixes a bug, but the buggy version was never released, so no need to add anything to the changelog.
* [x] I ran `tools/formatting/check-format` and everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by MakisH** [comment]
This does fix #1032 for me. I do not understand the change, though.

**Comment by KyleDavisSA** [comment]
For the quasi-Newton scheme, the `x^0` variable is always zero unless the initial write data is specified. In PR https://github.com/precice/precice/pull/1004, the initial write data is read in, but is not stored in the variable `cplData->previousIteration` for the QN method. That means in the `concatenateCouplingData` function in `BaseQNAcceleration`, `x^0` is always zero and never updated with the initial write data.

https://github.com/precice/precice/blob/bd0e158aa0cc795ba0c7b227cf1c086c73cbc896/src/acceleration/BaseQNAcceleration.cpp#L466

The 1D elastic tube test case is sensitive to this initial write data. The function `storeIteration()` updates the `previousIteration` values in:

https://github.com/precice/precice/blob/bd0e158aa0cc795ba0c7b227cf1c086c73cbc896/src/cplscheme/CouplingData.cpp#L38-L41

Adding this during  `exchangeInitialData` solved this problem.

**Comment by BenjaminRodenberg** [comment]
Good find and thanks for the explanation! This is something I oversaw in #1004. 

Any idea why some of the tests are failing now? Do you think we should write a specific test to avoid this kind of bug in the future? I'll look into it more closely tomorrow.

**Comment by KyleDavisSA** [comment]
I think a test is necessary. I will look into a test, that writes initial data and checks that value against `x^0` values.

**Comment by BenjaminRodenberg** [comment]
> I think a test is necessary. I will look into a test, that writes initial data and checks that value against `x^0` values.

Then I will wait until you trigger me again or something pops up here. Right?

**Review by BenjaminRodenberg — COMMENTED** [review]
I guess we also have to add `storeIteration` at the right places in `MultiCouplingScheme`:

https://github.com/precice/precice/blob/54707b3902af7d79b28ac276f304c31c6fcf5433/src/cplscheme/MultiCouplingScheme.cpp#L67-L82

**Comment by KyleDavisSA** [comment]
Is there a potential bug in the SerialTests? Below is an output from the test:

```
/__w/precice/precice/src/precice/tests/SerialTests.cpp(401): error: in "PreciceTests/Serial/testExplicitWithDataInitialization": check 2.0 == valueDataB has failed [2 != 0]. Absolute value exceeds tolerance [|2| > 1e-09]
```

SolverB writes the initial data of 2

https://github.com/precice/precice/blob/f71e555ca03c6b0f11443088a3b651b6e747033d/src/precice/tests/SerialTests.cpp#L418-L421

and SolverA reads in the initial data

https://github.com/precice/precice/blob/f71e555ca03c6b0f11443088a3b651b6e747033d/src/precice/tests/SerialTests.cpp#L398-L401

However the test still says the the solverB data is zero. SolverA should not be reading the values before SolverB sets them?

**Comment by uekerman** [comment]
> However the test still says the the solverB data is zero. SolverA should not be reading the values before SolverB sets them?

Not sure I understand what you mean, but the test looks correct. Not the test is buggy, preCICE is buggy.

**Comment by fsimonis** [comment]
Shouldn't the receiving solver skip the call to initializeData?

Sender:
* is initializeData required?
* write Data(2) 
* initializeData
* mark as done

Receiver
* initialize (receives here)
* read data = 2

Actually, initializeData should throw an error if it is called without being required to.

**Comment by BenjaminRodenberg** [comment]
I did another quick test comparing 3ff0899092862ad6f081df033ca9b51d0041befa (pre #1004) and 54707b3 (current state of this PR): I ran the 1d-elastic-tube cpp version https://github.com/precice/tutorials/commit/46ce8abee8dea365005da40f6e016a12f4bd97fd and compared the `precice-{Fluid,Solid}-iterations.log`. Here nothing suspicous shows up. I interpret this as a good sign and will dig deeper.

**Comment by BenjaminRodenberg** [comment]
With this version the tests work and also the elastic-tube is ok. However, I would like to add a test that catches the underlying problem. I'm also not yet sure whether actually all additions to the code are necessary.

# Todos

- [ ] Develop a test that fails for 40eca9d and succeeds for 8197993
- [ ] Refactor #1036, if necessary

**Comment by BenjaminRodenberg** [comment]
This PR is from my perspective ready. I would still suggest to merge #1050 first.

**Comment by KyleDavisSA** [comment]
This PR closes #1034 and #1032, but does it also work in the expected manner for the newly constructed tests in PR https://github.com/precice/precice/pull/1050 ?

All tests pass now with this PR.

**Comment by BenjaminRodenberg** [comment]
> This PR closes #1034 and #1032, but does it also work in the expected manner for the newly constructed tests in PR #1050 ?
> 
> All tests pass now with this PR.

When I tried this out a while ago: yes. You can locally merge this branch into `i_1032_test` (#1050) an run the tests. Then all tests (especially the previously failing ones) should succeed.

**Comment by fsimonis** [comment]
Can we merge the tests into this PR, see if all is well and finally merge the fix?

**Pull request merged**
