### PR TITLE
Improve errors messages of section 1.6

### PR DESCRIPTION
**Pull request by BenjaminRueth**
Improves error messages of section 1.6 in #698.

Notes:

* Trying to move configuration errors into `CplSchemeConfig.cpp`
* Some error messages are skipped until #689 is merged.

### CODE REVIEW

**Comment by BenjaminRueth** [comment]
I just realized that I accidentally merged many of the changes that belong to this PR (#744) already via #689 when I added the commit https://github.com/precice/precice/pull/689/commits/f08392219212aa6c4350153f4b4d9ab24d619b86 to #689. 

This makes the content of #744 currently more or less trivial. I will now finish the todos from section 1.6 #698 in this PR. For the review of #744 it makes sense to also take https://github.com/precice/precice/pull/689/commits/f08392219212aa6c4350153f4b4d9ab24d619b86 into consideration.

**Comment by BenjaminRueth** [comment]
> I just realized that I accidentally merged many of the changes that belong to this PR (#744) already via #689 when I added the commit [f083922](https://github.com/precice/precice/commit/f08392219212aa6c4350153f4b4d9ab24d619b86) to #689.
> 
> This makes the content of #744 currently more or less trivial. I will now finish the todos from section 1.6 #698 in this PR. For the review of #744 it makes sense to also take [f083922](https://github.com/precice/precice/commit/f08392219212aa6c4350153f4b4d9ab24d619b86) into consideration.

I fixed this issue for `src/cplscheme/config/CouplingSchemeConfig.cpp` via https://github.com/precice/precice/commit/ec736a5663757b97286d2d8553c808b64f2091ad. Note that some changes that should technically also belong to this PR (mainly changing `PRECICE_CHECK` to `PRECICE_ASSERT`, if appropriate in `BaseCouplingScheme.cpp`) I decided to leave everything as it is. I think it is not really worth the additional work, since the important part of this PR are the changes in the error messages that are introduced in `src/cplscheme/config/CouplingSchemeConfig.cpp`. These changes are now again visible in this PR.

**Comment by BenjaminRueth** [comment]
https://github.com/precice/precice/tree/remove_check_configuration should be merged into `develop` first. This PR is ready for review.

**Comment by atotoun** [comment]
Looks good to me :+1:

**Pull request merged**
