### PR TITLE
Fix VTK exporter

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

@MakisH

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I stuck to C++17 features.
* [ ] I stuck to CMake version 3.22.1.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by MakisH** [comment]
System tests run: https://github.com/precice/tutorials/actions/runs/11802465944

```
gh workflow run run_testsuite_manual.yml -f suites=elastic_tube_1d_test -f build_args=PLATFORM:ubuntu_2204,PRECICE_REF:b21a269cfc99f6e4b44b5162d42fd9b06d8a48df,PRECICE_PRESET:optimized-debug,PYTHON_BINDINGS_REF:v3.1.2,CALCULIX_VERSION:2.20,CALCULIX_ADAPTER_REF:2a5a73a,FENICS_ADAPTER_REF:3de561d,OPENFOAM_EXECUTABLE:openfoam2312,OPENFOAM_ADAPTER_REF:20b4617,SU2_VERSION:7.5.1,SU2_ADAPTER_REF:64d4aff,TUTORIALS_REF:70ad482 -f systests_branch=system-tests-debug --ref=system-tests-debug
```

**Comment by MakisH** [comment]
The original issue now seems to be fixed, but the system tests fail at the comparison stage:

```
field-compare-1  | Comparing files in the directories '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/precice-exports' and '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/reference-results-unpacked/fluid-cpp_solid-cpp'
field-compare-1  | 
field-compare-1  | Comparing '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/precice-exports/Fluid-Nodes-Mesh-Solid.dt75.vtk'
field-compare-1  |       and '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/reference-results-unpacked/fluid-cpp_solid-cpp/Fluid-Nodes-Mesh-Solid.dt75.vtk'
field-compare-1  |   Reading '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/precice-exports/Fluid-Nodes-Mesh-Solid.dt75.vtk'
field-compare-1  |   Reading '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/reference-results-unpacked/fluid-cpp_solid-cpp/Fluid-Nodes-Mesh-Solid.dt75.vtk'
field-compare-1  |    -- Comparing the field 'CrossSectionLength': FAILED
field-compare-1  |      -- Report: Deviation above tolerance detected -> [4.6778309865465e-310] vs. [0.] ([100.00] %)
field-compare-1  |      -- Predicate: DefaultEquality (abs_tol: 0., rel_tol: 3.e-07)
field-compare-1  |   Wrote diff into '/runs/elastic-tube-1d_fluid-cpp-solid-cpp_2024-11-12-182437/precice-exports/diff_Fluid-Nodes-Mesh-Solid.dt75.vtk.vtu'
field-compare-1  |   File comparison FAILED with 2 PASSED / 1 FAILED / 0 SKIPPED
```

There seems to be one entry (the first one of `CrossSectionLength` with seemingly uninitialized value):

```
SCALARS CrossSectionLength double
LOOKUP_TABLE default
4.67783098654649297e-310
0.00000000000000000e+00
-3.01211157334909149e+03
-3.01300424293654669e+03
-3.01384813881716173e+03
```

**Comment by MakisH** [comment]
New system tests run: https://github.com/precice/tutorials/actions/runs/11813648940

**Comment by MakisH** [comment]
Looking into the results of the [`elastic_tube_1d_test`](https://github.com/precice/tutorials/actions/runs/11814761148), I see that there are regressions above 1% in pressure:

```
fieldcompare dir -rtol 1e-2 --ignore-missing-reference-files precice-exports/ reference-results-unpacked/fluid-python_solid-python/

...

[ ======= ] 404 file comparisons performed
[ PASSED  ] 392 file comparisons
[ SKIPPED ] 4 file comparisons
[ FAILED  ] 12 file comparisons, listed below:
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt39.vtk: ('Pressure')
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt48.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt69.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt68.vtk: ('Pressure')
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt18.vtk: ('Pressure')
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt98.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt18.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt98.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt48.vtk: ('Pressure')
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt69.vtk: ('Pressure')
[ FAILED  ] Solid-Nodes-Mesh-Solid.dt68.vtk: ('Pressure')
[ FAILED  ] Fluid-Nodes-Mesh-Solid.dt39.vtk: ('Pressure')
```

This is probably unrelated to the original issue, but it is still a regression.

**Comment by MakisH** [comment]
@fsimonis yes, I believe that the issue should not originate from this repository or the exporters. We could have probably concluded this earlier, as it only appears in the Python-related tests and not in the C++.

I would suggest merging this already, so that I continue with more testing in #2052.

Feel free to remove all the bisection branches, and thanks a lot for your help there.

**Review by MakisH — APPROVED** [review]

**Comment by uekerman** [comment]
Let's also add an integration test here.

**Comment by fsimonis** [comment]
@uekerman Correct, this is a hack as the solution is #2132, which breaks most reference results.

@MakisH Is it possible to ignore missing data in files? I would really avoid hacking this in shape.

**Comment by MakisH** [comment]
I would prefer to change one thing at a time, otherwise we cannot know whether we also bring unintended regressions along.

Why not merge this now in develop, and merge #2132 on top, after we know that the results are consistent? It is not that develop is already bug-free in this regard anyway, and the other PR is ready.

**Comment by MakisH** [comment]
> @MakisH Is it possible to ignore missing data in files? I would really avoid hacking this in shape.

We can ignore fields in fieldcompare, yes.

**Comment by MakisH** [comment]
Just continuing documenting here for now (I know it is not the best place):

- I can reproduce the issue when running the system tests locally
- Results regressions do **not** appear in the elastic-tube-1d {fluid-cpp/solid-python, fluid-cpp/solid-cpp}, flow-over-heated-plate fluid-openfoam/solid-openfoam, perpendicular-flap fluid-openfoam/solid-calculix.
- The results regression appears in the elastic-tube-1d fluid-python/solid-python (almost exclusively pressure), as well as in the flow-over-heated-plate fluid-openfoam/solid-nutils (only heat flux).
- There are two more system tests that currently fail at the FEniCS installation.

Common in the two failing cases is that the regression appears in data that the Python-based code writes.

**Comment by fsimonis** [comment]
I'll merge this PR to get the fix into develop.
Once we figure out the regression, we can fix it, merge #2132 and generate new reference data.

**Pull request merged**
