### PR TITLE
Release v2.2.0

### PR DESCRIPTION
**Pull request by fsimonis**
## How to work with this template

* [x] assign a release manager, who takes care of the process
* [x] assign each point below to a responsible person, before you continue. Use `@member`.

Only the release manager should update this post (even tickboxes, due to race conditions in editing). Everybody else should comment on the PR with the progress.

## Step by step guide

* [x] Look over [`CHANGELOG.md`](https://github.com/precice/precice/blob/develop/CHANGELOG.md) (all)
   * Add things, if necessary
   * Extract summary
   * Fix wording and tense
   * Sort the entries lexicographically
* [x] Merge master to develop (No commits after the release on master)
* [x] Check code base w.r.t code formatting (run [`precice/tools/formatting/check-format`](https://github.com/precice/precice/blob/develop/tools/formatting/check-format)) and reformat if required (run [`precice/tools/formatting/format-all`](https://github.com/precice/precice/blob/develop/tools/formatting/format-all))
* [x] Create branch `release-N` from develop. If needed, `git rebase develop`.
* [x] Open PR from `release-N` to `master` (use [this template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md))
* [ ] Do regression tests using the release branch (specific revision) _list below :arrow_down:_ (all)
* [ ] Fix potential problems on release branch (all)
* [ ] Look over the [Roadmap](https://www.precice.org/fundamentals-roadmap.html) and update entries.
* [x] Run `tools/releasing/bumpversion.sh MAJOR.MINOR.PATCH` to bump the version
* [x] Verify the version changes in:
   * [x] [CHANGELOG](https://github.com/precice/precice/blob/develop/CHANGELOG.md)
   * [x] [CMakeLists.txt](https://github.com/precice/precice/blob/develop/CMakeLists.txt)
   * [x] [debian changelog](https://github.com/precice/precice/blob/develop/tools/releasing/packaging/debian/changelog)
   * [x] (prepare independent release) [Python bindings](https://github.com/precice/python-bindings) @BenjaminRodenberg 
   * [x] (prepare independent release, if necessary!) [MATLAB bindings](https://github.com/precice/matlab-bindings) @BenjaminRodenberg 
* [x] Commit the version bump
* [ ] Draft message to mailing list @fsimonis 
* [ ] Write a draft "blog post" on [Discourse](https://precice.discourse.group/)
* [ ] Approve the PR with at least two reviews (all)
* [ ] Merge PR to master ( use `git merge --no-ff release-N` )
* [ ] Tag release on master `vN` and verify by running `git describe --tags`
* [ ] Merge back to develop and verify by running `git describe --tags`
* [ ] Push master and push the `vN` tag
* [ ] [Draft a new release on GitHub](https://github.com/precice/precice/releases/new)
* [ ] Update documentation (all)
   * [ ] Update [XML configuration reference](https://github.com/precice/precice.github.io/blob/master/_includes/xmlreference.md)
   * [ ] Update version in [precice/precice.github.io](https://github.com/precice/precice.github.io):
      * `_config.yml`
      * `_data/sidebars/docs_sidebar.yml`
* [ ] Generate packages and upload to the draft release
   * [ ] Latest Ubuntu LTS
   * [ ] Latest Ubuntu
* [ ] Publish the GitHub release

## Regression Tests

Run all these tests manually on your system. If you succeed, please write a comment with the revisions of the components that you used below. Example: https://github.com/precice/precice/pull/507#issuecomment-530432289 and update the table.

Branches to test:
* precice: `precice-v2.2.0`
* python:  [`release_v2.2.0.1`](https://github.com/precice/python-bindings/tree/release_v2.2.0.1)
* matlab:  [`release_v2.2.0.1`](https://github.com/precice/matlab-bindings/tree/release_v2.2.0.1)
* rest: master

| State | Success | Failure | Skipped |
| --- | --- | --- | --- |
| Write | `:o:` | `:x:` | `:fast_forward:` |
| Read | :o: | :x: | :fast_forward: |

| State | Tester | Test |
| --- | --- | --- |
| [:o:](https://github.com/precice/precice/pull/949#issuecomment-762732185) | @IshaanDesai | SU2 / CalculiX [flap_perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/SU2-CalculiX) |
| :o:  | @MakisH | OpenFOAM / OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) serial + parallel |
| :o: | @MakisH  | OpenFOAM / OpenFOAM - NP mapping in OpenFOAM [flow_over_plate](https://github.com/precice/openfoam-adapter/tree/master/tutorials/CHT/flow-over-plate) |
| :o: | @MakisH | OpenFOAM / CalculiX FSI [flap perp](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp/OpenFOAM-CalculiX) |
| :o:  | @MakisH   | OpenFOAM / CalculiX FSI - NP mapping in CalculiX [3D_Tube](https://github.com/precice/tutorials/tree/develop/FSI/3D_Tube/OpenFOAM-CalculiX) |
| :o: | @MakisH  | OpenFOAM / CalculiX / OpenFOAM CHT [heat_exchanger](https://github.com/precice/tutorials/tree/develop/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX) |
| :o: | @MakisH | OpenFOAM / deal.II [flap_perp_2D](https://github.com/precice/tutorials/tree/develop/FSI/flap_perp_2D/OpenFOAM-deal.II) (linear + non-linear, serial + parallel) |
| :o: | @MakisH | OpenFOAM / deal.II [flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-deal.II) |
| [:x:](https://github.com/precice/precice/pull/949#issuecomment-762897526) |  @MakisH | OpenFOAM / deal.II [FSI cylinderFlap_2D](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap_2D/OpenFOAM-deal.II) |
| [:x:](https://github.com/precice/precice/pull/949#issuecomment-762897526) | @MakisH | OpenFOAM / deal.II [FSI cylinderFlap](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap_2D/OpenFOAM-deal.II) |
| :o:  | @IshaanDesai | OpenFOAM / FEniCS [flap_perp](https://github.com/precice/tutorials/tree/master/FSI/flap_perp/OpenFOAM-FEniCS) |
| :o: | @IshaanDesai  | OpenFOAM / FEniCS [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-fenics) |
| :o: | @IshaanDesai | OpenFOAM / FEniCS [cylinderFlap, only run first few minutes](https://github.com/precice/tutorials/tree/develop/FSI/cylinderFlap/OpenFOAM-FEniCS) |
| :o: #951  | @uekerman | OpenFOAM / Nutils [flow-over-plate](https://github.com/precice/tutorials/tree/master/CHT/flow-over-plate/buoyantPimpleFoam-nutils) |
| :o: | @BenjaminRodenberg  | FEniCS / FEniCS [partitioned-heat](https://github.com/precice/tutorials/tree/master/HT/partitioned-heat/fenics-fenics) |
| :o: | @IshaanDesai | SU2 / FEniCS flap_perp |
| :o: | @BenjaminRodenberg | MATLAB / MATLAB [ODEs](https://github.com/precice/matlab-bindings/tree/develop/tutorial) |
| :o: | @fsimonis  | 1D-ElasticTube [C++](https://github.com/precice/elastictube1d/tree/develop/cxx) | 
| :o: | @BenjaminRodenberg  | 1D-ElasticTube [Python](https://github.com/precice/elastictube1d/tree/develop/python) |
| :o: | @MakisH | Solverdummy [Fortran module](https://github.com/precice/fortran-module/tree/develop/examples/solverdummy) | 
| :o: | @BenjaminRodenberg  | Solverdummy [Python](https://github.com/precice/python-bindings/tree/develop/solverdummy) |
| :o: | @BenjaminRodenberg  | Solverdummy [MATLAB](https://github.com/precice/matlab-bindings/tree/develop/solverdummy) |
| :o: | @uekerman | Alya |
| :skull_and_crossbones:  | | ~~ExaFSA: Ateles / FASTEST~~ |
| :o: | @atotoun | SuperMUC Build |
| :o: | @atotoun | Ateles / Ateles (SuperMUC) |

## Post-release

* [ ] Update Arch Linux AUR Package
* [ ] Update Spack recipe

### Release new version for bindings (to ensure compatibility with newest preCICE version)

- [ ] [Fortan module](https://github.com/precice/fortran-module/compare/master...develop)
- [ ] [MATLAB bindings](https://github.com/precice/matlab-bindings/compare/master...develop)
- [ ] [python bindings](https://github.com/precice/python-bindings/compare/master...develop)

### Marketing

* [ ] Finalize post on [Discourse](https://precice.discourse.group/)
* [ ] Write on [Gitter](https://gitter.im/precice/Lobby)
* [ ] Send announcement to the [mailing list](https://mailman.informatik.uni-stuttgart.de/mailman/listinfo/precice)
* [ ] [CFD-Online](https://www.cfd-online.com/Forum/news.cgi/form/0)
* [ ] NADigest
* [ ] Post on [Twitter](https://twitter.com/preCICE_org) (additionally to the automatic)
* [ ] Post on [ResearchGate](https://www.researchgate.net/project/preCICE)
* [ ] Post on LinkedIn (individuals)
* [ ] Submit a short article to the [Quartl](https://www.in.tum.de/en/i05/further-activities/quartl/)

### Misc

* [ ] Update the [PR template](https://github.com/precice/precice/blob/add_PR_template/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md)

### CODE REVIEW

**Comment by BenjaminRodenberg** [comment]
Here are the links to the bindings branches:

* python: [release_v2.2.0.1](https://github.com/precice/python-bindings/tree/release_v2.2.0.1)
* matlab: [release_v2.2.0.1](https://github.com/precice/matlab-bindings/tree/release_v2.2.0.1)

@fsimonis please edit in description.

**Comment by fsimonis** [comment]
1D-ElasticTube C++ works

**Comment by IshaanDesai** [comment]
`FSI/flap_perp/SU2-CalculiX/` case works and the expected result of a *diverged simulation* is observed. The following components are used:
SU2-Adapter: https://github.com/precice/su2-adapter/commit/9761fd8e22d785592e912ccb6aad5d22e0dcaf29
CalculiX-Adapter: https://github.com/precice/calculix-adapter/commit/eadedeef0a1a4e2e2c7a5d164faccd7b40012347
`tutorials`: https://github.com/precice/tutorials/commit/5f4031fc7e45807dca787a525569b39a1909d2a3
preCICE: https://github.com/precice/precice/commit/79d4581eed7ce1b0fd2990edcd04ad2c86681fd5

**Comment by atotoun** [comment]
preCICE compiles on superMUC. 
The Ateles-Ateles(Pulse within a cubic domain) runs and results look reasonable.

**Comment by MakisH** [comment]
OpenFOAM adapter tests with master and commit 8ae5f061ab26ae059b8cdcf304089306f9ce7227 (September 2)
Note that we should **not** release develop at the moment, as we have a potential bug: https://github.com/precice/openfoam-adapter/issues/149

- :heavy_check_mark: OpenFOAM-OpenFOAM CHT flow over plate works and the results look visually correct:
   - Normal case, serial and parallel
   - Nearest-projection case, serial

**Comment by BenjaminRodenberg** [comment]
Solverdummy Python works

**Comment by BenjaminRodenberg** [comment]
Solverdummy MATLAB works

**Comment by IshaanDesai** [comment]
`FSI/flap_perp_2D/SU2-FEniCS` case works and the result is verified by verifying the tip displacement plot at the end of the simulation. The following components are used:
SU2-Adapter: https://github.com/precice/su2-adapter/commit/9761fd8e22d785592e912ccb6aad5d22e0dcaf29
FEniCS-Adapter: https://github.com/precice/fenics-adapter/commit/bd7482706374fd78905ab649c7c643859522723f
tutorials: https://github.com/precice/tutorials/commit/5f4031fc7e45807dca787a525569b39a1909d2a3
preCICE: https://github.com/precice/precice/commit/79d4581eed7ce1b0fd2990edcd04ad2c86681fd5

**Comment by BenjaminRodenberg** [comment]
MATLAB ODE tutorial works. Ran into an issue (https://github.com/precice/matlab-bindings/issues/28), but I think this is an old one we did document yet. So: Everything ok.

**Comment by BenjaminRodenberg** [comment]
Elastictube Python works.

**Comment by uekerman** [comment]
Alya works.

**Comment by MakisH** [comment]
For the CalculiX cases I am using CalculiX 2.16 and the adapter from master (eadedeef0a1a4e2e2c7a5d164faccd7b40012347, Nov17).

For the deal.II cases I am using dea.II 9.2 and the adapter from master (1d148462224d0148ee77ebd6d7f93612c0adcd8e, Dec6).

- :heavy_check_mark: OpenFOAM-CalculiX FSI perpendicular flap works in serial and results look ok.
- (:heavy_check_mark:) OpenFOAM-CalculiX FSI 3D tube seems to work in serial. **Note:** I only let it run until time 0.0010. @KyleDavisSA you may want to run this longer and look at the resutls. Somehow I feel it takes longer to compute.
- :heavy_check_mark:  OpenFOAM-deal.II FSI 3D perpendicular flap (linear) works in serial and the results look ok.
- :heavy_check_mark: OpenFOAM-deal.II FSI 2D perpendicular flap (linear) works in serial and the results look ok.
- :heavy_check_mark: OpenFOAM-deal.II FSI 2D perpendicular flap (nonlinear) works in parallel and the results look ok.
- :x:  OpenFOAM-deal.II FSI 2D cylinder-flap (linear) starts, but deal.II fails early with the following error:
   ```
   ---[precice] ERROR:  Attempting to add a zero vector to the quasi-Newton V matrix. This means that the residual in two  consecutive iterations is identical. There is probably something wrong in your adapter. Maybe you always write the same (or only incremented) data or you call advance without providing  new data first.
   ```
   @DavidSCN I guess this is expected?
    - Note that we somehow don't have the `Solid/dealii_output` directory there, which makes deal.II complain. We are anyway restructuring the tutorials, so this is not really an issue to solve now.
 - :x: Same for the 3D OpenFOAM-deal.II FSI cylinder-flap (linear).

**Comment by MakisH** [comment]
:heavy_check_mark:  The fortran module and the respective solverdummy from master (9826f277e3302cc1aef50741530538bd9d8d23c7, Jul20) work.

**Comment by MakisH** [comment]
(:heavy_check_mark:) The OpenFOAM-CalculiX-OpenFOAM heat exchanger works, at least for 30 coupling time windows. No results are written for this time range, however, so @KyleDavisSA feel free to check deeper if needed.

**Comment by IshaanDesai** [comment]
`FSI/flap_perp_2D/OpenFOAM-FEniCS` case works and the result is verified by verifying the tip displacement plot at the end of the simulation. The following components are used:
OpenFOAM-Adapter: https://github.com/precice/openfoam-adapter/commit/8ae5f061ab26ae059b8cdcf304089306f9ce7227
FEniCS-Adapter: https://github.com/precice/fenics-adapter/commit/bd7482706374fd78905ab649c7c643859522723f
tutorials: https://github.com/precice/tutorials/commit/5f4031fc7e45807dca787a525569b39a1909d2a3
preCICE: https://github.com/precice/precice/commit/79d4581eed7ce1b0fd2990edcd04ad2c86681fd5

**Comment by BenjaminRodenberg** [comment]
FEniCS - FEniCS partitioned heat in different flavours:

* `python3 heat.py -n & python3 heat.py -d`
* `mpirun -np 2 python3 heat.py -n & mpirun -np 2 python3 heat.py -d`
* `python3 heat.py -n -i complex & python3 heat.py -d -i complex`
* `mpirun -np 2 python3 heat.py -n -i complex & mpirun -np 2 python3 heat.py -d -i complex`

**Comment by DavidSCN** [comment]
@MakisH the issue has been solved in the turek benchmark. The cylinder test case will no longer exist once the restructuring is done. I think this is related to https://github.com/precice/tutorials/issues/94.

**Comment by IshaanDesai** [comment]
`CHT/flow-over-plate/buoyantPimpleFoam-fenics/` case works and the result is verified by viewing the results in ParaView at the end of the simulation. The following components are used:
OpenFOAM-Adapter: https://github.com/precice/openfoam-adapter/commit/8ae5f061ab26ae059b8cdcf304089306f9ce7227
FEniCS-Adapter: https://github.com/precice/fenics-adapter/commit/bd7482706374fd78905ab649c7c643859522723f
tutorials: https://github.com/precice/tutorials/commit/5f4031fc7e45807dca787a525569b39a1909d2a3
preCICE: https://github.com/precice/precice/commit/79d4581eed7ce1b0fd2990edcd04ad2c86681fd5

**Comment by IshaanDesai** [comment]
`FSI/cylinderFlap_2D/OpenFOAM-FEniCS` case works and the result is verified by checking the parameter output for the first few minutes of the run. The following components are used:
OpenFOAM-Adapter: https://github.com/precice/openfoam-adapter/commit/8ae5f061ab26ae059b8cdcf304089306f9ce7227
FEniCS-Adapter: https://github.com/precice/fenics-adapter/commit/bd7482706374fd78905ab649c7c643859522723f
tutorials: https://github.com/precice/tutorials/commit/5f4031fc7e45807dca787a525569b39a1909d2a3
preCICE: https://github.com/precice/precice/commit/79d4581eed7ce1b0fd2990edcd04ad2c86681fd5

**Comment by uekerman** [comment]
OpenFOAM - Nutils fails. We presumably introduced a bug in https://github.com/precice/precice/commit/dc3350d9548c6afbd490064a0978db4a2b92a386, which makes configuration of an Aitken underrelaxation impossible.

**Comment by BenjaminRodenberg** [comment]
@fsimonis Can you add the following links to the template for the python/MATLAB bindings release?

* https://github.com/precice/python-bindings/blob/develop/docs/ReleaseGuide.md
* https://github.com/precice/matlab-bindings/blob/develop/docs/ReleaseGuide.md

Is the template stored somewhere or do we always copy-paste it from the last release? Could not find it in the repo. If you tell me where the template lies, I can also open a PR.

**Comment by MakisH** [comment]
> @fsimonis Can you add the following links to the template for the python/MATLAB bindings release?
> 
>     * https://github.com/precice/python-bindings/blob/develop/docs/ReleaseGuide.md
> 
>     * https://github.com/precice/matlab-bindings/blob/develop/docs/ReleaseGuide.md
> 
> 
> Is the template stored somewhere or do we always copy-paste it from the last release? Could not find it in the repo. If you tell me where the template lies, I can also open a PR.

I moved them here: https://github.com/precice/precice/tree/develop/tools/releasing/PULL_REQUEST_TEMPLATE

**Comment by BenjaminRodenberg** [comment]
@fsimonis I'll take care of everything documentation-related mentioned in https://github.com/precice/precice.github.io/pull/13.

**Comment by fsimonis** [comment]
The configuration bug was fixed in #951

**Review by uekerman — APPROVED** [review]

**Review by MakisH — APPROVED** [review]

**Review by IshaanDesai — APPROVED** [review]

**Comment by MakisH** [comment]
Spack PR opened: https://github.com/spack/spack/pull/21166

**Pull request merged**
