### PR TITLE
WIP Add a Git verification step to updateSourceFiles

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds:
* A verification step to the source generation
* IGNORE_PATTERNS to ignore bindings etc.
* CONFIGURED_SOURCES to add the result of `.in` files such as `src/versions.hpp.in`

```console
$ tools/updateSourceFiles.py
Detected:
 sources: 296
 public: 5
 tests: 70
The source tree contains files not tracked by git.
Please do one of the following with these files:
  - track them using 'git add'
  - add them to IGNORE_PATTERNS in this script
  - add them to CONFIGURED_SOURCES in this script!
Files:
  src/precice/bindings/python/BadPythonBoy.hpp
  src/precice/bindings/python/BadPythonBoy.cpp
  src/precice/BadBoy.cpp
VERIFICATION FAILED
```

```console
$ tools/updateSourceFiles.py         
Detected:
 sources: 296
 public: 5
 tests: 70
Git did not run successfully.
These sources are UNVERIFIED!
Generating CMake files
Writing Files
 ./src/sources.cmake
 ./src/tests.cmake
done
```

### CODE REVIEW

**Comment by floli** [comment]
I don't think that's a good idea. If I understand correctly, the script wants to force me to either add the files to git or modify the script in order to compile? Seriously? Sometime I just want to play with some modifications and backup `cp file.cpp file.backup`. Or I add a new source file, but I want to compile before checking in, or have them laying around for some time.

What about issuing the warning and do the generation anyway?

**Comment by fsimonis** [comment]
@floli That's the intention, yes.
In your example, the `file.backup` wouldn't be picked up anyhow as it is not a `.cpp` file. Adding files to the index also does not mean that you commit them.

We could of course display the warning and generate the cmake files anyhow.

**Comment by floli** [comment]
> We could of course display the warning and generate the cmake files anyhow.

Under that condition, I am cool with the changes, but if I read the code correctly, it does not do that right now. (`if not_tracked: return 1`)

Please refrain from enforcing automatism.

**Comment by fsimonis** [comment]
@floli The script now prints the warning and generates the cmake files.

_Is selective automatism really automatism?_

**Pull request merged**
