### PR TITLE
Update PR template

### PR DESCRIPTION
**Pull request by BenjaminRueth**
Applying changes according to latest version of #657

### CODE REVIEW

**Comment by fsimonis** [comment]
Further feedback:
* Order: formatting, release branch, bumpversion, verify versions, release PR, regression tests , fix problems, 
* Add point "external releases" to post-release.
* Move python and matlab releases to post-release/external-releases
* Maybe add spack recepie to regression tests as it tends to reveal problems in the build system

**Comment by fsimonis** [comment]
Another thought is that maybe the PR is not the right place for keeping track of all these steps.
The PR only exists in a subinterval of the actual release workflow, so this template should maybe be an issue template.

**Comment by BenjaminRueth** [comment]
@fsimonis Can you do a review?

One thing I was wondering about while merging: What has happened to the [packages for Ubuntu](https://github.com/precice/precice/blob/885d0de534d2ee35c4d772305e8eba8793aba238/.github/PULL_REQUEST_TEMPLATE/release_pull_request_template.md#post-release)? Do we have to add this to the template or do we already have everything that's required?

Feel free to merge, if your review does not discover any further points.

**Comment by fsimonis** [comment]
@BenjaminRueth You mean this? :wink: 
image

**Pull request merged**
