### PR TITLE
Add Watchpoint Reinitialisation

### PR DESCRIPTION
**Pull request by fsimonis**
This PR 
* changes `WatchPoint` so that it can be reinitialized,
* adds the required `TXTTableWriter::reset()`.
* rework watchpoint test to check time series
* add watchpoint test to check reinitialization

This is a part of #225

### CODE REVIEW

**Comment by uekerman** [comment]
Looks correct now. Still, to be on the safe side, it would be good if the `WatchPointTest` covers a case where the modified mesh also modifies the watched value.

**Comment by fsimonis** [comment]
I added the requested case. The tests now actually check the output.

**Comment by fsimonis** [comment]
This PR needs a complete rework after the code reformat and the change of the test framework

**Comment by fsimonis** [comment]
@uekerman I reworked the branch and added a test to check the reinitalization.
The new tests has two watchpoints that project on the point of the same edge. Then it adds an edge so that one of the two points projects to the new edge.

**Pull request merged**
