### PR TITLE
Python Adapter for preCICE

### PR DESCRIPTION
**Pull request by saumiJ**
1. Currently required local build of the `PySolverInterface` library (work in progress to include it in scons)
2. Does not support `getMeshHandle`, `inquireClosestMesh` and `inquireVoxelPosition`
3. Instructions for use included in the `readme`

### CODE REVIEW

**Comment by davidsblom** [comment]
Awesome! Do you have an example where the python interface is used in a FSI setting? For example the 1D tube flow test case. Would be very helpful.

**Comment by saumiJ** [comment]
Sure! But the example is a dummy one, as in the non-linear fluid solver has not been built yet.

I can add the example in the Python Adapter folder for now, if that is okay.

**Comment by uekerman** [comment]
no, please ass the dummy example to the elastictube repo. whether it's dummy or not, does not play such a crucial role.

**Comment by davidsblom** [comment]
thanks a lot for this! Mark will be grateful :+1:

**Comment by uekerman** [comment]
i currently get an error
```PySolverInterface.pyx:7:0: 'shared_ptr.pxd' not found```
```PySolverInterface.pyx:7:27: Name 'shared_ptr' not declared in module 'libcpp.memory'```
```PySolverInterface.pyx:9:0: 'unique_ptr.pxd' not found```

maybe, there is a problem with the cython version.
anyway, could you please add some specification in the readme what are prerequisites, etc 
```Cython version 0.20.1post0```

**Comment by floli** [comment]
I get another error message:
```
florian@asaru ~/precice/src/precice/adapters/python (git)-[develop] % python2 setup.py build_ext --inplace
running build_ext
cythoning PySolverInterface.pyx to PySolverInterface.cpp
building 'PySolverInterface' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/home/florian/precice -I/usr/include/python2.7 -c PySolverInterface.cpp -o build/temp.linux-x86_64-2.7/PySolverInterface.o -I/home/florian/precice -Wall -std=c++11 -pthread
In file included from /usr/include/python2.7/Python.h:121:0,
                 from PySolverInterface.cpp:4:
PySolverInterface.cpp: In function 'PyObject* newarrayobject(PyTypeObject*, Py_ssize_t, arraydescr*)':
/usr/include/python2.7/pyerrors.h:221:74: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
 #define PyErr_BadInternalCall() _PyErr_BadInternalCall(__FILE__, __LINE__)
                                                                          ^
PySolverInterface.cpp:681:9: note: in expansion of macro 'PyErr_BadInternalCall'
         PyErr_BadInternalCall();
         ^
g++ -pthread -shared -Wl,-O1,--sort-common,--as-needed,-z,relro build/temp.linux-x86_64-2.7/PySolverInterface.o -L/usr/lib -lpython2.7 -o /home/florian/precice/src/precice/adapters/python/PySolverInterface.so -L/home/florian/precice/build/last/ -lprecice -lboost_system -lboost_filesystem -pthread -Wl,-rpath -Wl,/usr/lib/openmpi -Wl,--enable-new-dtags -L/usr/lib/openmpi -lmpi_cxx -lmpi
/usr/bin/ld: /home/florian/precice/build/last//libprecice.a(Constants.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/home/florian/precice/build/last//libprecice.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```

**Comment by floli** [comment]
Importing PySolverInterface gives an error
```
florian@asaru ~/precice/src/precice/adapters/python (git)-[develop] % python2
Python 2.7.11 (default, Dec  6 2015, 15:43:46) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, sys
>>> precice_root = os.getenv('PRECICE_ROOT')
>>> precice_python_adapter_root = precice_root+"/src/precice/adapters/python"
>>> precice_python_adapter_root
'/home/florian/precice/src/precice/adapters/python'
>>> sys.path.insert(0, precice_python_adapter_root)
>>> import PySolverInterface
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/florian/precice/src/precice/adapters/python/PySolverInterface.so: undefined symbol: PetscLogPLB
```

**Comment by saumiJ** [comment]
@uekerman: The `memory` module was indeed updated in the latest cython version. I will add this information in the readme.
@floli: I will try to replicate the error you get.

**Comment by uekerman** [comment]
my above problem was resolved by the newer cython version.
then, i could reproduce florian's problem.
this problem disappears with petsc=off.
finally, i then ran into an MPI problem.
@saumiJ can you completely run the testcase?
to fully test it, you could simply couple the C++ fluid solver with the python structure solver.

**Comment by saumiJ** [comment]
@uekerman: Yep, the Python solvers as they are run all the way through with the given config file.

Can you post the error you get here?

**Comment by uekerman** [comment]
```
uekerman@riemann ~/Repos/elastictube1d/PythonDummy (git)-[master] % python StructureSolver.py precice-config.xml 100
Starting Structure Solver...
N: 100
Configure preCICE...
 | 09:39:29     | precice::impl::SolverInterfaceImpl::configure()         | [PRECICE] Run in coupling mode
[riemann:04038] mca: base: component_find: unable to open /usr/lib/openmpi/lib/openmpi/mca_paffinity_hwloc: perhaps a missing symbol, or compiled for a different version of Open MPI? (ignored)
```
how does he decide which mpi he uses for running?

**Comment by saumiJ** [comment]
For me, when using `mpi` as the option for `m2n` in the configuration file, the code crashed with the same error message as @uekerman.

`mca: base: component_find: unable to open /usr/lib/openmpi/lib/openmpi/mca_paffinity_hwloc: perhaps a missing symbol, or compiled for a different version of Open MPI? (ignored)`

and a list of 4 to 5 similar error messages.

The fix to this, is to reinstall openmpi with the flag `--disable-dlopen`. More explanation can be found [here](http://www.open-mpi.de/faq/?category=mpi-apps#static-mpi-apps).

**Comment by floli** [comment]
Recompiling openmpi can hardly be considered a fix, it's simply not possible on most machines.

BTW: Since this pull request is closed, should be move the discussion to an issue. Perferably at https://github.com/saumiJ/precice (Saumitra, you need to enable issues for your fork).

**Comment by saumiJ** [comment]
Okay, I've enabled issues there.

I'll try to get more info on this error.

**Comment by uekerman** [comment]
Well, it's already sth. Saumitra, can you give us a brief explanation what the option does? I did not read through the complete FAQ entry :)
To get further inside, you could try running it on supermuc with intel mpi.
If you create an issue at your fork, do we get push notifications? Probably not, right? Can you add us as observers there?

**Comment by floli** [comment]
> If you create an issue at your fork, do we get push notifications? Probably not, right? Can you add us as observers there?
Just **Watch** the repo

**Comment by davidsblom** [comment]
hi! is this problem already fixed? we got the same error as Benjamin and we cannot recompile MPI on the cluster.

**Comment by uekerman** [comment]
saumitra wanted to have a look into the python mpi problem again. especially to try with intel mpi on supermuc. we plan to document the status quo in the precice wiki

**Comment by davidsblom** [comment]
Awesome! Can you mention it here when the wiki is updated? Then I'll receive a notification :+1:

**Comment by davidsblom** [comment]
for your information, we managed to get the python script going. needed to recompile a whole list of software:

precice, python, openmpi, scipy, numpy, setuptools

**Comment by saumiJ** [comment]
did you have to recompile openmpi with the `--disable-dlopen` flag?

**Comment by davidsblom** [comment]
we did manage to recompile openmpi with the `--disable-dlopen` flag. However, it's not optimal, since the connection between nodes is now over the standard ethernet cable and not the high speed link thus limiting performance.

**Comment by uekerman** [comment]
good news, guys. we solved the MPI issue. credits go to Lucia!
mpi4py does the job. compare 
[this entry](http://stackoverflow.com/questions/36156822/error-when-starting-open-mpi-in-mpi-init-via-python).
now, you do not need to recompile MPI.

i updated the readme and the 1d-elastictube dummies. 
please let me know whether this also works for you.

**Pull request merged**
