### PR TITLE
Replace c-style casts by static cast

### PR DESCRIPTION
**Pull request by DavidSCN**
## Main changes of this PR
Replace c-style casts by static cast as part #999 .

## Motivation and additional information
C-style casts are discouraged

## Author's checklist

* [ ] I added a changelog file with this PR number in `docs/changelog/` if there are noteworthy changes.
* [x] I ran `tools/formatting/check-format` and everything is formatted correctly.
* [x] I sticked to C++14 features.
* [x] I sticked to CMake version 3.10.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?
* [ ] (more questions/tasks)

### CODE REVIEW

**Review by fsimonis — COMMENTED** [review]
I am confused about the casts from `Eigen::VectorXd::Zero()` to `Eigen::VectorXd`.
This shouldn't be necessary.

**Comment by DavidSCN** [comment]
@fsimonis you mean the cast itself rather than the proposed change, right?

**Comment by DavidSCN** [comment]
@fsimonis `append` is templated and the compiler cannot deduce the argument from the return type of `zero`.

**Review by fsimonis — APPROVED** [review]
We should have a look at this eigen append again in the future.

**Comment by DavidSCN** [comment]
A pretty simple solution would be the following:
```diff
-template <typename Derived1>
+template <typename VectorType>
 void append(
-    Eigen::VectorXd &                       v,
-    const Eigen::PlainObjectBase<Derived1> &app)
+    Eigen::VectorXd & v,
+    const VectorType &app)
```
so that the compiler can easily deduce the argument.

**Comment by fsimonis** [comment]
Given that appending zero is a common call to append, we could introduce `appendZeros(vec, count)`.
This makes things even less verbose.

**Pull request merged**
