### PR TITLE
Fix profiling tests checking for pandas instead of polars

### PR DESCRIPTION
**Pull request by fsimonis**
## Main changes of this PR

This PR changes the profiling tests to
* check for polars instead of pandas in simple tests
* set the venv correctly for the one multi directory test
* add more debug output in the tests and while installing polars
* correctly analyse 2 rank runs.

## Author's checklist

* [ ] I used the [`pre-commit` hook](https://precice.org/dev-docs-dev-tooling.html#setting-up-pre-commit) to prevent dirty commits and used `pre-commit run --all` to format old commits.
* [ ] I added a changelog file with `make changelog` if there are user-observable changes since the last release.
* [ ] I added a test to cover the proposed changes in our test suite.
* [ ] For breaking changes: I documented the changes in the appropriate [porting guide](https://precice.org/couple-your-code-porting-overview.html).
* [ ] I sticked to C++17 features.
* [ ] I sticked to CMake version 3.16.3.
* [ ] I squashed / am about to squash all commits that should be seen as one.

## Reviewers' checklist

* [ ] Does the changelog entry make sense? Is it formatted correctly?
* [ ] Do you understand the code changes?

### CODE REVIEW

**Comment by MakisH** [comment]
I get the same warning as in #1766:

```
Installing polars in a python venv to allow for full profiling tests.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'polars'
CMake Warning at tools/profiling/CMakeLists.txt:33 (message):
  Installing polars in a venv failed.
```

The `ModuleNotFoundError` part is new.

and yes, configuration does succeed anyway. I just get the warning.

**Comment by fsimonis** [comment]
Strange, but then you could also call pip via the venv python

```
./build/TestOutput/venv/bin/python -m pip list
./build/TestOutput/venv/bin/python -m pip install polars
```

**Comment by MakisH** [comment]
> Strange, but then you could also call pip via the venv python
> 
> ```
> ./build/TestOutput/venv/bin/python -m pip list
> ./build/TestOutput/venv/bin/python -m pip install polars
> ```

```shell
~/repos/precice/precice [fix-profiling-tests]$ ./build/TestOutput/venv/bin/python -m pip list
/home/gc/repos/precice/precice/build/TestOutput/venv/bin/python: No module named pip
```

**Comment by MakisH** [comment]
Debugging with @fsimonis:

```
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
-- Found Python 3.10.12
-- Found Python3: /usr/include/python3.10 (found version "3.10.12") found components: Development NumPy Interpreter Development.Module Development.Embed 
-- Found Python 3.10.12 with NumPy 1.21.5
-- Validating LibPython
-- Validating LibPython - success
-- Validating NumPy
-- Validating NumPy - success
```

```bash
~/repos/precice/precice/build [fix-profiling-tests]$ python -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/gc/repos/precice/precice/build/venv/bin/python3
```

Installing python-venv worked for me:

```bash
sudo apt install python3.10-venv
```

**Comment by MakisH** [comment]
Now I am getting a nice info message:

```
Python venv not found. Please install python-venv or python3-venv for full profiling tests.
```

With the package installed:

```
Installing polars in a python venv to allow for full profiling tests.
```

**Review by MakisH — APPROVED** [review]

**Pull request merged**
