### PR TITLE
Fix vector access patterns

### PR DESCRIPTION
**Pull request by oguzziya**
This PR changes vector (or array) access patterns in tests to have more robust testing. Changes include
- All the standard library accesses are changed from `[ ]` to `.at()`. Only exception is `std::map` only while constructing the map
- There were some C-style heap-allocated arrays, these are transformed into `std::vector`
- Access for `Eigen`  containers are changed from `[ ]` to `( )` because of two reasons: First, It makes it easier to detect problematic `[ ]` usages; Second, only `Eigen::Vector` supports `[ ]` and in the case of `Eigen::Array` usage becomes consistent. This part is open to discussion actually.

### CODE REVIEW

**Review by fsimonis — APPROVED** [review]
There are too many changes to review all of them, but the tests pass and most of the changes look fine.

I am in favour of the eigen3 access change. This makes things more clear and is in line with the matrix access too.

All in all. Good work!

This PR shows that we are doing too much work manually.
We need to gradually migrate parts to [`testing::equals`](https://www.precice.org/doxygen/develop/namespaceprecice_1_1testing.html#a6a116337529290bbb1bf2545b5fb315a) for eigen (and`std::vector<double>`) and `BOOST_CHECK_EQUAL_COLLECTIONS`.

**Comment by oguzziya** [comment]
I skipped `ParallelTests` since there were too many C-like arrays, I think it is related to the ease of use for the interface. Should I change them to `std` containers?

**Comment by uekerman** [comment]
I unassigned me as reviewer. 4 eyes are enough here I guess :grin:

**Comment by fsimonis** [comment]
> I skipped `ParallelTests` since there were too many C-like arrays, I think it is related to the ease of use for the interface. Should I change them to `std` containers?

Let's do this in a separate PR. We should definitely modernize our tests.

**Pull request merged**
