### PR TITLE
Improve CMake Packaging

### PR DESCRIPTION
**Pull request by fsimonis**
This PR generally improves packaging with CMake by:

* using the `GNUInstallDirs`
* setting the correct SOVERSION
* generating a  correctly named debian package
* adding a correct changelog for the package
* making lintian happy

Furthermore, this PR:
* Enables C++11 as actual requirement
* Disables compiler extensions
* Fixes the use of an uninitialized (but harmless) variable

Future work:
* Split the package into a runtime and developer package
* Hide symbol names #623 

**TODO**
* [x] Add version and system to package name

### CODE REVIEW

**Comment by fsimonis** [comment]
The current state generates a correctly named package:
```
$ make package
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Revision status: Detection failed
[  0%] Built target GitRevision
[ 62%] Built target precice
[ 63%] Built target binprecice
[100%] Built target testprecice
Run CPack packaging tool...
CPack: Create package using TGZ
CPack: Install projects
CPack: - Run preinstall target for: preCICE
CPack: - Install project: preCICE
CPack: Create package
CPack: - package: /tmp/precice/libprecice1-1.6.1-xenial.tar.gz generated.
CPack: - checksum file: /tmp/precice/libprecice1-1.6.1-xenial.tar.gz.sha256 generated.
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: preCICE
CPack: - Install project: preCICE
CPack: Create package
CPack: - package: /tmp/precice/libprecice1-1.6.1-xenial.deb generated.
CPack: - checksum file: /tmp/precice/libprecice1-1.6.1-xenial.deb.sha256 generated.

$ lintian libprecice1-1.6.1-xenial.deb 
N: 1 tag overridden (1 warning)
```

_Note: This does not break the systemtests!_ :tada:

**Comment by MakisH** [comment]
> The downside is that we have to update the `changelog` after each release.

Could you elaborate on this?

If we do this need, it would be a good idea to also add it to our release PR template.

**Comment by fsimonis** [comment]
@MakisH at every release, we also release a new debian package which simply represents the unpatched upstream release.

For 1.6.1, I had to add the following section to the [changelog](https://github.com/fsimonis/precice/blob/improve-cmake/tools/packaging/debian/changelog):
```
libprecice1 (1.6.1) experimental; urgency=low

  * New upstream release 1.6.1

 -- the preCICE developers <precice@mailman.informatik.uni-stuttgart.de>  Fri, 13 Sep 2019 11:07:42 +0200
```
This is of course trivial to auto-generate.

**Comment by fsimonis** [comment]
This should be added to #509

**Pull request merged**
